// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module gaussian_relu_array_ap_fixed_15u_array_ap_fixed_16_6_5_3_0_15u_relu_config16_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer15_out_dout,
        layer15_out_num_data_valid,
        layer15_out_fifo_cap,
        layer15_out_empty_n,
        layer15_out_read,
        layer16_out_din,
        layer16_out_num_data_valid,
        layer16_out_fifo_cap,
        layer16_out_full_n,
        layer16_out_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [554:0] layer15_out_dout;
input  [1:0] layer15_out_num_data_valid;
input  [1:0] layer15_out_fifo_cap;
input   layer15_out_empty_n;
output   layer15_out_read;
output  [239:0] layer16_out_din;
input  [1:0] layer16_out_num_data_valid;
input  [1:0] layer16_out_fifo_cap;
input   layer16_out_full_n;
output   layer16_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer15_out_read;
reg layer16_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer15_out_blk_n;
reg    layer16_out_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln51_fu_301_p2;
reg   [0:0] icmp_ln51_reg_666;
reg    ap_block_state1;
reg   [15:0] out_data_reg_671;
wire   [0:0] icmp_ln51_1_fu_317_p2;
reg   [0:0] icmp_ln51_1_reg_676;
reg   [15:0] out_data_19_reg_681;
wire   [0:0] icmp_ln51_2_fu_333_p2;
reg   [0:0] icmp_ln51_2_reg_686;
reg   [15:0] out_data_20_reg_691;
wire   [0:0] icmp_ln51_3_fu_349_p2;
reg   [0:0] icmp_ln51_3_reg_696;
reg   [15:0] out_data_21_reg_701;
wire   [0:0] icmp_ln51_4_fu_365_p2;
reg   [0:0] icmp_ln51_4_reg_706;
reg   [15:0] trunc_ln3_reg_711;
wire   [0:0] icmp_ln51_5_fu_381_p2;
reg   [0:0] icmp_ln51_5_reg_716;
reg   [15:0] trunc_ln52_1_reg_721;
wire   [0:0] icmp_ln51_6_fu_397_p2;
reg   [0:0] icmp_ln51_6_reg_726;
reg   [15:0] trunc_ln52_2_reg_731;
wire   [0:0] icmp_ln51_7_fu_413_p2;
reg   [0:0] icmp_ln51_7_reg_736;
reg   [15:0] trunc_ln52_3_reg_741;
wire   [0:0] icmp_ln51_8_fu_429_p2;
reg   [0:0] icmp_ln51_8_reg_746;
reg   [15:0] trunc_ln52_4_reg_751;
wire   [0:0] icmp_ln51_9_fu_445_p2;
reg   [0:0] icmp_ln51_9_reg_756;
reg   [15:0] trunc_ln52_5_reg_761;
wire   [0:0] icmp_ln51_10_fu_461_p2;
reg   [0:0] icmp_ln51_10_reg_766;
reg   [15:0] trunc_ln52_6_reg_771;
wire   [0:0] icmp_ln51_11_fu_477_p2;
reg   [0:0] icmp_ln51_11_reg_776;
reg   [15:0] trunc_ln52_7_reg_781;
wire   [0:0] icmp_ln51_12_fu_493_p2;
reg   [0:0] icmp_ln51_12_reg_786;
reg   [15:0] trunc_ln52_8_reg_791;
wire   [0:0] icmp_ln51_13_fu_509_p2;
reg   [0:0] icmp_ln51_13_reg_796;
reg   [15:0] trunc_ln52_9_reg_801;
wire   [0:0] icmp_ln51_14_fu_525_p2;
reg   [0:0] icmp_ln51_14_reg_806;
reg   [15:0] trunc_ln52_s_reg_811;
wire   [36:0] trunc_ln44_fu_157_p1;
wire   [36:0] trunc_ln44_1_fu_161_p4;
wire   [36:0] trunc_ln44_2_fu_171_p4;
wire   [36:0] trunc_ln44_3_fu_181_p4;
wire   [36:0] trunc_ln44_4_fu_191_p4;
wire   [36:0] trunc_ln44_5_fu_201_p4;
wire   [36:0] trunc_ln44_6_fu_211_p4;
wire   [36:0] trunc_ln44_7_fu_221_p4;
wire   [36:0] trunc_ln44_8_fu_231_p4;
wire   [36:0] trunc_ln44_9_fu_241_p4;
wire   [36:0] trunc_ln44_s_fu_251_p4;
wire   [36:0] trunc_ln44_10_fu_261_p4;
wire   [36:0] trunc_ln44_11_fu_271_p4;
wire   [36:0] trunc_ln44_12_fu_281_p4;
wire   [36:0] trunc_ln44_13_fu_291_p4;
wire   [15:0] select_ln51_14_fu_625_p3;
wire   [15:0] select_ln51_13_fu_619_p3;
wire   [15:0] select_ln51_12_fu_613_p3;
wire   [15:0] select_ln51_11_fu_607_p3;
wire   [15:0] select_ln51_10_fu_601_p3;
wire   [15:0] select_ln51_9_fu_595_p3;
wire   [15:0] select_ln51_8_fu_589_p3;
wire   [15:0] select_ln51_7_fu_583_p3;
wire   [15:0] select_ln51_6_fu_577_p3;
wire   [15:0] select_ln51_5_fu_571_p3;
wire   [15:0] select_ln51_4_fu_565_p3;
wire   [15:0] select_ln51_3_fu_559_p3;
wire   [15:0] select_ln51_2_fu_553_p3;
wire   [15:0] select_ln51_1_fu_547_p3;
wire   [15:0] select_ln51_fu_541_p3;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((layer16_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln51_10_reg_766 <= icmp_ln51_10_fu_461_p2;
        icmp_ln51_11_reg_776 <= icmp_ln51_11_fu_477_p2;
        icmp_ln51_12_reg_786 <= icmp_ln51_12_fu_493_p2;
        icmp_ln51_13_reg_796 <= icmp_ln51_13_fu_509_p2;
        icmp_ln51_14_reg_806 <= icmp_ln51_14_fu_525_p2;
        icmp_ln51_1_reg_676 <= icmp_ln51_1_fu_317_p2;
        icmp_ln51_2_reg_686 <= icmp_ln51_2_fu_333_p2;
        icmp_ln51_3_reg_696 <= icmp_ln51_3_fu_349_p2;
        icmp_ln51_4_reg_706 <= icmp_ln51_4_fu_365_p2;
        icmp_ln51_5_reg_716 <= icmp_ln51_5_fu_381_p2;
        icmp_ln51_6_reg_726 <= icmp_ln51_6_fu_397_p2;
        icmp_ln51_7_reg_736 <= icmp_ln51_7_fu_413_p2;
        icmp_ln51_8_reg_746 <= icmp_ln51_8_fu_429_p2;
        icmp_ln51_9_reg_756 <= icmp_ln51_9_fu_445_p2;
        icmp_ln51_reg_666 <= icmp_ln51_fu_301_p2;
        out_data_19_reg_681 <= {{layer15_out_dout[62:47]}};
        out_data_20_reg_691 <= {{layer15_out_dout[99:84]}};
        out_data_21_reg_701 <= {{layer15_out_dout[136:121]}};
        out_data_reg_671 <= {{layer15_out_dout[25:10]}};
        trunc_ln3_reg_711 <= {{layer15_out_dout[173:158]}};
        trunc_ln52_1_reg_721 <= {{layer15_out_dout[210:195]}};
        trunc_ln52_2_reg_731 <= {{layer15_out_dout[247:232]}};
        trunc_ln52_3_reg_741 <= {{layer15_out_dout[284:269]}};
        trunc_ln52_4_reg_751 <= {{layer15_out_dout[321:306]}};
        trunc_ln52_5_reg_761 <= {{layer15_out_dout[358:343]}};
        trunc_ln52_6_reg_771 <= {{layer15_out_dout[395:380]}};
        trunc_ln52_7_reg_781 <= {{layer15_out_dout[432:417]}};
        trunc_ln52_8_reg_791 <= {{layer15_out_dout[469:454]}};
        trunc_ln52_9_reg_801 <= {{layer15_out_dout[506:491]}};
        trunc_ln52_s_reg_811 <= {{layer15_out_dout[543:528]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((layer16_out_full_n == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer16_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((layer16_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer15_out_blk_n = layer15_out_empty_n;
    end else begin
        layer15_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer15_out_read = 1'b1;
    end else begin
        layer15_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        layer16_out_blk_n = layer16_out_full_n;
    end else begin
        layer16_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer16_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        layer16_out_write = 1'b1;
    end else begin
        layer16_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((layer16_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (layer15_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign icmp_ln51_10_fu_461_p2 = (($signed(trunc_ln44_s_fu_251_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_11_fu_477_p2 = (($signed(trunc_ln44_10_fu_261_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_12_fu_493_p2 = (($signed(trunc_ln44_11_fu_271_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_13_fu_509_p2 = (($signed(trunc_ln44_12_fu_281_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_14_fu_525_p2 = (($signed(trunc_ln44_13_fu_291_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_1_fu_317_p2 = (($signed(trunc_ln44_1_fu_161_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_2_fu_333_p2 = (($signed(trunc_ln44_2_fu_171_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_3_fu_349_p2 = (($signed(trunc_ln44_3_fu_181_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_4_fu_365_p2 = (($signed(trunc_ln44_4_fu_191_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_5_fu_381_p2 = (($signed(trunc_ln44_5_fu_201_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_6_fu_397_p2 = (($signed(trunc_ln44_6_fu_211_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_7_fu_413_p2 = (($signed(trunc_ln44_7_fu_221_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_8_fu_429_p2 = (($signed(trunc_ln44_8_fu_231_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_9_fu_445_p2 = (($signed(trunc_ln44_9_fu_241_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_301_p2 = (($signed(trunc_ln44_fu_157_p1) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign layer16_out_din = {{{{{{{{{{{{{{{select_ln51_14_fu_625_p3}, {select_ln51_13_fu_619_p3}}, {select_ln51_12_fu_613_p3}}, {select_ln51_11_fu_607_p3}}, {select_ln51_10_fu_601_p3}}, {select_ln51_9_fu_595_p3}}, {select_ln51_8_fu_589_p3}}, {select_ln51_7_fu_583_p3}}, {select_ln51_6_fu_577_p3}}, {select_ln51_5_fu_571_p3}}, {select_ln51_4_fu_565_p3}}, {select_ln51_3_fu_559_p3}}, {select_ln51_2_fu_553_p3}}, {select_ln51_1_fu_547_p3}}, {select_ln51_fu_541_p3}};

assign select_ln51_10_fu_601_p3 = ((icmp_ln51_10_reg_766[0:0] == 1'b1) ? trunc_ln52_6_reg_771 : 16'd0);

assign select_ln51_11_fu_607_p3 = ((icmp_ln51_11_reg_776[0:0] == 1'b1) ? trunc_ln52_7_reg_781 : 16'd0);

assign select_ln51_12_fu_613_p3 = ((icmp_ln51_12_reg_786[0:0] == 1'b1) ? trunc_ln52_8_reg_791 : 16'd0);

assign select_ln51_13_fu_619_p3 = ((icmp_ln51_13_reg_796[0:0] == 1'b1) ? trunc_ln52_9_reg_801 : 16'd0);

assign select_ln51_14_fu_625_p3 = ((icmp_ln51_14_reg_806[0:0] == 1'b1) ? trunc_ln52_s_reg_811 : 16'd0);

assign select_ln51_1_fu_547_p3 = ((icmp_ln51_1_reg_676[0:0] == 1'b1) ? out_data_19_reg_681 : 16'd0);

assign select_ln51_2_fu_553_p3 = ((icmp_ln51_2_reg_686[0:0] == 1'b1) ? out_data_20_reg_691 : 16'd0);

assign select_ln51_3_fu_559_p3 = ((icmp_ln51_3_reg_696[0:0] == 1'b1) ? out_data_21_reg_701 : 16'd0);

assign select_ln51_4_fu_565_p3 = ((icmp_ln51_4_reg_706[0:0] == 1'b1) ? trunc_ln3_reg_711 : 16'd0);

assign select_ln51_5_fu_571_p3 = ((icmp_ln51_5_reg_716[0:0] == 1'b1) ? trunc_ln52_1_reg_721 : 16'd0);

assign select_ln51_6_fu_577_p3 = ((icmp_ln51_6_reg_726[0:0] == 1'b1) ? trunc_ln52_2_reg_731 : 16'd0);

assign select_ln51_7_fu_583_p3 = ((icmp_ln51_7_reg_736[0:0] == 1'b1) ? trunc_ln52_3_reg_741 : 16'd0);

assign select_ln51_8_fu_589_p3 = ((icmp_ln51_8_reg_746[0:0] == 1'b1) ? trunc_ln52_4_reg_751 : 16'd0);

assign select_ln51_9_fu_595_p3 = ((icmp_ln51_9_reg_756[0:0] == 1'b1) ? trunc_ln52_5_reg_761 : 16'd0);

assign select_ln51_fu_541_p3 = ((icmp_ln51_reg_666[0:0] == 1'b1) ? out_data_reg_671 : 16'd0);

assign start_out = real_start;

assign trunc_ln44_10_fu_261_p4 = {{layer15_out_dout[443:407]}};

assign trunc_ln44_11_fu_271_p4 = {{layer15_out_dout[480:444]}};

assign trunc_ln44_12_fu_281_p4 = {{layer15_out_dout[517:481]}};

assign trunc_ln44_13_fu_291_p4 = {{layer15_out_dout[554:518]}};

assign trunc_ln44_1_fu_161_p4 = {{layer15_out_dout[73:37]}};

assign trunc_ln44_2_fu_171_p4 = {{layer15_out_dout[110:74]}};

assign trunc_ln44_3_fu_181_p4 = {{layer15_out_dout[147:111]}};

assign trunc_ln44_4_fu_191_p4 = {{layer15_out_dout[184:148]}};

assign trunc_ln44_5_fu_201_p4 = {{layer15_out_dout[221:185]}};

assign trunc_ln44_6_fu_211_p4 = {{layer15_out_dout[258:222]}};

assign trunc_ln44_7_fu_221_p4 = {{layer15_out_dout[295:259]}};

assign trunc_ln44_8_fu_231_p4 = {{layer15_out_dout[332:296]}};

assign trunc_ln44_9_fu_241_p4 = {{layer15_out_dout[369:333]}};

assign trunc_ln44_fu_157_p1 = layer15_out_dout[36:0];

assign trunc_ln44_s_fu_251_p4 = {{layer15_out_dout[406:370]}};

endmodule //gaussian_relu_array_ap_fixed_15u_array_ap_fixed_16_6_5_3_0_15u_relu_config16_s
