-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity gaussian_shift_line_buffer_array_ap_fixed_16_6_5_3_0_10u_config13_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read7 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read8 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read9 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_137_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_137_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_137_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_29 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_29_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_138_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_138_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_138_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_28 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_28_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_139_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_139_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_139_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_27 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_27_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_140_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_140_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_140_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_26 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_26_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_141_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_141_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_141_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_25 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_25_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_142_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_142_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_142_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_24 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_24_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_143_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_143_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_143_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_23 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_23_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_144_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_144_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_144_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_22 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_22_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_145_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_145_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_145_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_21 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_21_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_146_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_146_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_146_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_20 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_20_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_157_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_157_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_157_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_147 : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_147_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_158_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_158_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_158_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_148 : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_148_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_159_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_159_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_159_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_149 : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_149_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_160_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_160_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_160_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_150 : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_150_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_161_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_161_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_161_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_151 : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_151_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_162_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_162_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_162_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_152 : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_152_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_163_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_163_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_163_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_153 : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_153_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_164_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_164_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_164_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_154 : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_154_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_165_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_165_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_165_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_155 : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_155_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_166_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_166_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_166_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_156 : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_156_ap_vld : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC );
end;


architecture behav of gaussian_shift_line_buffer_array_ap_fixed_16_6_5_3_0_10u_config13_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_9_ce0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_9_we0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_9_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_8_ce0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_8_we0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_8_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_7_ce0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_7_we0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_7_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_6_ce0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_6_we0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_6_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_5_ce0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_5_we0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_5_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_4_ce0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_4_we0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_4_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_3_ce0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_3_we0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_3_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_2_ce0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_2_we0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_2_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_1_ce0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_1_we0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_1_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_ce0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_we0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component gaussian_shift_line_buffer_array_ap_fixed_16_6_5_3_0_10u_config13_s_void_pooling2d_cl_5jm IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (0 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_9_U : component gaussian_shift_line_buffer_array_ap_fixed_16_6_5_3_0_10u_config13_s_void_pooling2d_cl_5jm
    generic map (
        DataWidth => 16,
        AddressRange => 2,
        AddressWidth => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv1_1,
        ce0 => void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_9_ce0,
        we0 => void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_9_we0,
        d0 => p_read,
        q0 => void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_9_q0);

    void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_8_U : component gaussian_shift_line_buffer_array_ap_fixed_16_6_5_3_0_10u_config13_s_void_pooling2d_cl_5jm
    generic map (
        DataWidth => 16,
        AddressRange => 2,
        AddressWidth => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv1_1,
        ce0 => void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_8_ce0,
        we0 => void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_8_we0,
        d0 => p_read1,
        q0 => void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_8_q0);

    void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_7_U : component gaussian_shift_line_buffer_array_ap_fixed_16_6_5_3_0_10u_config13_s_void_pooling2d_cl_5jm
    generic map (
        DataWidth => 16,
        AddressRange => 2,
        AddressWidth => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv1_1,
        ce0 => void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_7_ce0,
        we0 => void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_7_we0,
        d0 => p_read2,
        q0 => void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_7_q0);

    void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_6_U : component gaussian_shift_line_buffer_array_ap_fixed_16_6_5_3_0_10u_config13_s_void_pooling2d_cl_5jm
    generic map (
        DataWidth => 16,
        AddressRange => 2,
        AddressWidth => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv1_1,
        ce0 => void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_6_ce0,
        we0 => void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_6_we0,
        d0 => p_read3,
        q0 => void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_6_q0);

    void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_5_U : component gaussian_shift_line_buffer_array_ap_fixed_16_6_5_3_0_10u_config13_s_void_pooling2d_cl_5jm
    generic map (
        DataWidth => 16,
        AddressRange => 2,
        AddressWidth => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv1_1,
        ce0 => void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_5_ce0,
        we0 => void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_5_we0,
        d0 => p_read4,
        q0 => void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_5_q0);

    void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_4_U : component gaussian_shift_line_buffer_array_ap_fixed_16_6_5_3_0_10u_config13_s_void_pooling2d_cl_5jm
    generic map (
        DataWidth => 16,
        AddressRange => 2,
        AddressWidth => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv1_1,
        ce0 => void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_4_ce0,
        we0 => void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_4_we0,
        d0 => p_read5,
        q0 => void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_4_q0);

    void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_3_U : component gaussian_shift_line_buffer_array_ap_fixed_16_6_5_3_0_10u_config13_s_void_pooling2d_cl_5jm
    generic map (
        DataWidth => 16,
        AddressRange => 2,
        AddressWidth => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv1_1,
        ce0 => void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_3_ce0,
        we0 => void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_3_we0,
        d0 => p_read6,
        q0 => void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_3_q0);

    void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_2_U : component gaussian_shift_line_buffer_array_ap_fixed_16_6_5_3_0_10u_config13_s_void_pooling2d_cl_5jm
    generic map (
        DataWidth => 16,
        AddressRange => 2,
        AddressWidth => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv1_1,
        ce0 => void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_2_ce0,
        we0 => void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_2_we0,
        d0 => p_read7,
        q0 => void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_2_q0);

    void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_1_U : component gaussian_shift_line_buffer_array_ap_fixed_16_6_5_3_0_10u_config13_s_void_pooling2d_cl_5jm
    generic map (
        DataWidth => 16,
        AddressRange => 2,
        AddressWidth => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv1_1,
        ce0 => void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_1_ce0,
        we0 => void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_1_we0,
        d0 => p_read8,
        q0 => void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_1_q0);

    void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_U : component gaussian_shift_line_buffer_array_ap_fixed_16_6_5_3_0_10u_config13_s_void_pooling2d_cl_5jm
    generic map (
        DataWidth => 16,
        AddressRange => 2,
        AddressWidth => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv1_1,
        ce0 => void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_ce0,
        we0 => void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_we0,
        d0 => p_read9,
        q0 => void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_ce)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_ce)
    begin
        if (((ap_start = ap_const_logic_0) or (ap_const_logic_0 = ap_ce))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_137_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_137_i, void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_9_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_137_o <= void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_9_q0;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_137_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_137_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_137_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_137_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_137_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_138_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_138_i, void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_8_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_138_o <= void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_8_q0;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_138_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_138_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_138_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_138_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_138_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_139_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_139_i, void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_7_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_139_o <= void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_7_q0;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_139_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_139_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_139_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_139_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_139_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_140_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_140_i, void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_6_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_140_o <= void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_6_q0;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_140_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_140_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_140_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_140_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_140_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_141_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_141_i, void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_5_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_141_o <= void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_5_q0;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_141_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_141_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_141_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_141_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_141_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_142_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_142_i, void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_4_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_142_o <= void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_4_q0;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_142_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_142_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_142_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_142_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_142_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_143_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_143_i, void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_3_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_143_o <= void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_3_q0;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_143_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_143_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_143_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_143_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_143_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_144_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_144_i, void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_2_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_144_o <= void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_2_q0;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_144_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_144_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_144_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_144_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_144_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_145_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_145_i, void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_1_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_145_o <= void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_1_q0;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_145_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_145_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_145_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_145_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_145_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_146_o_assign_proc : process(ap_CS_fsm_state1, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_146_i, void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_146_o <= void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_q0;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_146_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_146_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_146_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_146_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_146_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_147 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_157_i;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_147_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_147_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_147_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_148 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_158_i;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_148_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_148_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_148_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_149 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_159_i;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_149_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_149_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_149_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_150 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_160_i;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_150_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_150_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_150_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_151 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_161_i;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_151_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_151_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_151_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_152 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_162_i;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_152_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_152_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_152_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_153 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_163_i;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_153_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_153_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_153_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_154 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_164_i;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_154_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_154_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_154_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_155 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_165_i;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_155_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_155_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_155_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_156 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_166_i;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_156_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_156_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_156_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_157_o_assign_proc : process(ap_CS_fsm_state1, p_read, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_157_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_157_o <= p_read;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_157_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_157_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_157_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_157_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_157_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_158_o_assign_proc : process(ap_CS_fsm_state1, p_read1, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_158_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_158_o <= p_read1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_158_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_158_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_158_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_158_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_158_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_159_o_assign_proc : process(ap_CS_fsm_state1, p_read2, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_159_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_159_o <= p_read2;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_159_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_159_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_159_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_159_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_159_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_160_o_assign_proc : process(ap_CS_fsm_state1, p_read3, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_160_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_160_o <= p_read3;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_160_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_160_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_160_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_160_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_160_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_161_o_assign_proc : process(ap_CS_fsm_state1, p_read4, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_161_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_161_o <= p_read4;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_161_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_161_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_161_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_161_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_161_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_162_o_assign_proc : process(ap_CS_fsm_state1, p_read5, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_162_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_162_o <= p_read5;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_162_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_162_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_162_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_162_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_162_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_163_o_assign_proc : process(ap_CS_fsm_state1, p_read6, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_163_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_163_o <= p_read6;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_163_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_163_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_163_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_163_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_163_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_164_o_assign_proc : process(ap_CS_fsm_state1, p_read7, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_164_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_164_o <= p_read7;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_164_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_164_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_164_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_164_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_164_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_165_o_assign_proc : process(ap_CS_fsm_state1, p_read8, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_165_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_165_o <= p_read8;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_165_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_165_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_165_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_165_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_165_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_166_o_assign_proc : process(ap_CS_fsm_state1, p_read9, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_166_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_166_o <= p_read9;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_166_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_166_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_166_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_166_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_166_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_20 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_146_i;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_20_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_20_ap_vld <= ap_const_logic_1;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_20_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_21 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_145_i;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_21_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_21_ap_vld <= ap_const_logic_1;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_21_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_22 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_144_i;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_22_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_22_ap_vld <= ap_const_logic_1;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_22_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_23 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_143_i;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_23_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_23_ap_vld <= ap_const_logic_1;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_23_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_24 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_142_i;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_24_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_24_ap_vld <= ap_const_logic_1;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_24_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_25 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_141_i;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_25_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_25_ap_vld <= ap_const_logic_1;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_25_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_26 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_140_i;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_26_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_26_ap_vld <= ap_const_logic_1;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_26_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_27 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_139_i;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_27_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_27_ap_vld <= ap_const_logic_1;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_27_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_28 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_138_i;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_28_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_28_ap_vld <= ap_const_logic_1;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_28_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_29 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_137_i;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_29_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_29_ap_vld <= ap_const_logic_1;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_29_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_1_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_1_ce0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_1_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_1_we0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_2_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_2_ce0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_2_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_2_we0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_3_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_3_ce0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_3_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_3_we0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_4_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_4_ce0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_4_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_4_we0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_4_we0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_5_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_5_ce0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_5_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_5_we0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_5_we0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_6_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_6_ce0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_6_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_6_we0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_6_we0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_7_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_7_ce0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_7_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_7_we0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_7_we0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_8_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_8_ce0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_8_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_8_we0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_8_we0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_9_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_9_ce0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_9_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_9_we0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_9_we0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_ce0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_we0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_10u_0_line_buffer_we0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
