-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity gaussian_dense_array_ap_fixed_15u_array_ap_fixed_37_17_5_3_0_10u_config17_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    layer16_out_dout : IN STD_LOGIC_VECTOR (239 downto 0);
    layer16_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer16_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer16_out_empty_n : IN STD_LOGIC;
    layer16_out_read : OUT STD_LOGIC;
    layer17_out_din : OUT STD_LOGIC_VECTOR (369 downto 0);
    layer17_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer17_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer17_out_full_n : IN STD_LOGIC;
    layer17_out_write : OUT STD_LOGIC );
end;


architecture behav of gaussian_dense_array_ap_fixed_15u_array_ap_fixed_37_17_5_3_0_10u_config17_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_8F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001111";
    constant ap_const_lv32_90 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010000";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101111";
    constant ap_const_lv32_B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_CF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001111";
    constant ap_const_lv32_D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010000";
    constant ap_const_lv32_DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011111";
    constant ap_const_lv32_E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100000";
    constant ap_const_lv32_EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101111";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal layer16_out_blk_n : STD_LOGIC;
    signal layer17_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal data_pack_fu_112_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_pack_reg_311 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal data_pack_15_reg_316 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_pack_16_reg_321 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_pack_17_reg_326 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_pack_18_reg_331 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_pack_19_reg_336 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_pack_20_reg_341 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_pack_21_reg_346 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_pack_22_reg_351 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_pack_23_reg_356 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_pack_24_reg_361 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_pack_25_reg_366 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_pack_26_reg_371 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_pack_27_reg_376 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_pack_28_reg_381 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_reg_386 : STD_LOGIC_VECTOR (36 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal res_1_reg_391 : STD_LOGIC_VECTOR (36 downto 0);
    signal res_2_reg_396 : STD_LOGIC_VECTOR (36 downto 0);
    signal res_3_reg_401 : STD_LOGIC_VECTOR (36 downto 0);
    signal res_4_reg_406 : STD_LOGIC_VECTOR (36 downto 0);
    signal res_5_reg_411 : STD_LOGIC_VECTOR (36 downto 0);
    signal res_6_reg_416 : STD_LOGIC_VECTOR (36 downto 0);
    signal res_7_reg_421 : STD_LOGIC_VECTOR (36 downto 0);
    signal res_8_reg_426 : STD_LOGIC_VECTOR (36 downto 0);
    signal res_9_reg_431 : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s_fu_93_ap_return_0 : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s_fu_93_ap_return_1 : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s_fu_93_ap_return_2 : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s_fu_93_ap_return_3 : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s_fu_93_ap_return_4 : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s_fu_93_ap_return_5 : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s_fu_93_ap_return_6 : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s_fu_93_ap_return_7 : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s_fu_93_ap_return_8 : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s_fu_93_ap_return_9 : STD_LOGIC_VECTOR (36 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component gaussian_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_0_val1 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_1_val2 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_2_val3 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_3_val4 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_4_val5 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_5_val6 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_6_val7 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_7_val8 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_8_val9 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_9_val10 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_10_val11 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_11_val12 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_12_val13 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_13_val14 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_14_val15 : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (36 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (36 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (36 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (36 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (36 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (36 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (36 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (36 downto 0);
        ap_return_8 : OUT STD_LOGIC_VECTOR (36 downto 0);
        ap_return_9 : OUT STD_LOGIC_VECTOR (36 downto 0) );
    end component;



begin
    grp_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s_fu_93 : component gaussian_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_0_val1 => data_pack_reg_311,
        data_1_val2 => data_pack_15_reg_316,
        data_2_val3 => data_pack_16_reg_321,
        data_3_val4 => data_pack_17_reg_326,
        data_4_val5 => data_pack_18_reg_331,
        data_5_val6 => data_pack_19_reg_336,
        data_6_val7 => data_pack_20_reg_341,
        data_7_val8 => data_pack_21_reg_346,
        data_8_val9 => data_pack_22_reg_351,
        data_9_val10 => data_pack_23_reg_356,
        data_10_val11 => data_pack_24_reg_361,
        data_11_val12 => data_pack_25_reg_366,
        data_12_val13 => data_pack_26_reg_371,
        data_13_val14 => data_pack_27_reg_376,
        data_14_val15 => data_pack_28_reg_381,
        ap_return_0 => grp_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s_fu_93_ap_return_0,
        ap_return_1 => grp_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s_fu_93_ap_return_1,
        ap_return_2 => grp_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s_fu_93_ap_return_2,
        ap_return_3 => grp_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s_fu_93_ap_return_3,
        ap_return_4 => grp_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s_fu_93_ap_return_4,
        ap_return_5 => grp_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s_fu_93_ap_return_5,
        ap_return_6 => grp_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s_fu_93_ap_return_6,
        ap_return_7 => grp_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s_fu_93_ap_return_7,
        ap_return_8 => grp_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s_fu_93_ap_return_8,
        ap_return_9 => grp_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s_fu_93_ap_return_9);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((layer17_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                data_pack_15_reg_316 <= layer16_out_dout(31 downto 16);
                data_pack_16_reg_321 <= layer16_out_dout(47 downto 32);
                data_pack_17_reg_326 <= layer16_out_dout(63 downto 48);
                data_pack_18_reg_331 <= layer16_out_dout(79 downto 64);
                data_pack_19_reg_336 <= layer16_out_dout(95 downto 80);
                data_pack_20_reg_341 <= layer16_out_dout(111 downto 96);
                data_pack_21_reg_346 <= layer16_out_dout(127 downto 112);
                data_pack_22_reg_351 <= layer16_out_dout(143 downto 128);
                data_pack_23_reg_356 <= layer16_out_dout(159 downto 144);
                data_pack_24_reg_361 <= layer16_out_dout(175 downto 160);
                data_pack_25_reg_366 <= layer16_out_dout(191 downto 176);
                data_pack_26_reg_371 <= layer16_out_dout(207 downto 192);
                data_pack_27_reg_376 <= layer16_out_dout(223 downto 208);
                data_pack_28_reg_381 <= layer16_out_dout(239 downto 224);
                data_pack_reg_311 <= data_pack_fu_112_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                res_1_reg_391 <= grp_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s_fu_93_ap_return_1;
                res_2_reg_396 <= grp_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s_fu_93_ap_return_2;
                res_3_reg_401 <= grp_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s_fu_93_ap_return_3;
                res_4_reg_406 <= grp_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s_fu_93_ap_return_4;
                res_5_reg_411 <= grp_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s_fu_93_ap_return_5;
                res_6_reg_416 <= grp_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s_fu_93_ap_return_6;
                res_7_reg_421 <= grp_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s_fu_93_ap_return_7;
                res_8_reg_426 <= grp_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s_fu_93_ap_return_8;
                res_9_reg_431 <= grp_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s_fu_93_ap_return_9;
                res_reg_386 <= grp_dense_latency_wrapper_ap_fixed_ap_fixed_37_17_5_3_0_config17_s_fu_93_ap_return_0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, layer17_out_full_n, ap_CS_fsm_state7, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((layer17_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(layer17_out_full_n)
    begin
        if ((layer17_out_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, layer16_out_empty_n)
    begin
                ap_block_state1 <= ((layer16_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, layer17_out_full_n, ap_CS_fsm_state7)
    begin
        if (((layer17_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    data_pack_fu_112_p1 <= layer16_out_dout(16 - 1 downto 0);

    internal_ap_ready_assign_proc : process(layer17_out_full_n, ap_CS_fsm_state7)
    begin
        if (((layer17_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    layer16_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, layer16_out_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer16_out_blk_n <= layer16_out_empty_n;
        else 
            layer16_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer16_out_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer16_out_read <= ap_const_logic_1;
        else 
            layer16_out_read <= ap_const_logic_0;
        end if; 
    end process;


    layer17_out_blk_n_assign_proc : process(layer17_out_full_n, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            layer17_out_blk_n <= layer17_out_full_n;
        else 
            layer17_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer17_out_din <= (((((((((res_9_reg_431 & res_8_reg_426) & res_7_reg_421) & res_6_reg_416) & res_5_reg_411) & res_4_reg_406) & res_3_reg_401) & res_2_reg_396) & res_1_reg_391) & res_reg_386);

    layer17_out_write_assign_proc : process(layer17_out_full_n, ap_CS_fsm_state7)
    begin
        if (((layer17_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            layer17_out_write <= ap_const_logic_1;
        else 
            layer17_out_write <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
