-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity gaussian_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config18_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    layer17_out_dout : IN STD_LOGIC_VECTOR (369 downto 0);
    layer17_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer17_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer17_out_empty_n : IN STD_LOGIC;
    layer17_out_read : OUT STD_LOGIC;
    layer18_out_din : OUT STD_LOGIC_VECTOR (159 downto 0);
    layer18_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer18_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer18_out_full_n : IN STD_LOGIC;
    layer18_out_write : OUT STD_LOGIC );
end;


architecture behav of gaussian_relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config18_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100101";
    constant ap_const_lv32_49 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001001";
    constant ap_const_lv32_4A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001010";
    constant ap_const_lv32_6E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101110";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_93 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010011";
    constant ap_const_lv32_94 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010100";
    constant ap_const_lv32_B8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111000";
    constant ap_const_lv32_B9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111001";
    constant ap_const_lv32_DD : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011101";
    constant ap_const_lv32_DE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011110";
    constant ap_const_lv32_102 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000010";
    constant ap_const_lv32_103 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000011";
    constant ap_const_lv32_127 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100111";
    constant ap_const_lv32_128 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101000";
    constant ap_const_lv32_14C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101001100";
    constant ap_const_lv32_14D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101001101";
    constant ap_const_lv32_171 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101110001";
    constant ap_const_lv37_0 : STD_LOGIC_VECTOR (36 downto 0) := "0000000000000000000000000000000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv32_54 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010100";
    constant ap_const_lv32_63 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100011";
    constant ap_const_lv32_79 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111001";
    constant ap_const_lv32_88 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001000";
    constant ap_const_lv32_9E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011110";
    constant ap_const_lv32_AD : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101101";
    constant ap_const_lv32_C3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000011";
    constant ap_const_lv32_D2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010010";
    constant ap_const_lv32_E8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101000";
    constant ap_const_lv32_F7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110111";
    constant ap_const_lv32_10D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001101";
    constant ap_const_lv32_11C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011100";
    constant ap_const_lv32_132 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110010";
    constant ap_const_lv32_141 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101000001";
    constant ap_const_lv32_157 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101010111";
    constant ap_const_lv32_166 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101100110";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal layer17_out_blk_n : STD_LOGIC;
    signal layer18_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln51_fu_211_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_reg_456 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal out_data_reg_461 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln51_15_fu_227_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_15_reg_466 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_data_22_reg_471 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln51_16_fu_243_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_16_reg_476 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_data_23_reg_481 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln51_17_fu_259_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_17_reg_486 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_data_24_reg_491 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln51_18_fu_275_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_18_reg_496 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln4_reg_501 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln51_19_fu_291_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_19_reg_506 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_s_reg_511 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln51_20_fu_307_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_20_reg_516 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_1_reg_521 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln51_21_fu_323_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_21_reg_526 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_2_reg_531 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln51_22_fu_339_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_22_reg_536 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_3_reg_541 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln51_23_fu_355_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_23_reg_546 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_4_reg_551 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_fu_117_p1 : STD_LOGIC_VECTOR (36 downto 0);
    signal trunc_ln44_s_fu_121_p4 : STD_LOGIC_VECTOR (36 downto 0);
    signal trunc_ln44_14_fu_131_p4 : STD_LOGIC_VECTOR (36 downto 0);
    signal trunc_ln44_15_fu_141_p4 : STD_LOGIC_VECTOR (36 downto 0);
    signal trunc_ln44_16_fu_151_p4 : STD_LOGIC_VECTOR (36 downto 0);
    signal trunc_ln44_17_fu_161_p4 : STD_LOGIC_VECTOR (36 downto 0);
    signal trunc_ln44_18_fu_171_p4 : STD_LOGIC_VECTOR (36 downto 0);
    signal trunc_ln44_19_fu_181_p4 : STD_LOGIC_VECTOR (36 downto 0);
    signal trunc_ln44_20_fu_191_p4 : STD_LOGIC_VECTOR (36 downto 0);
    signal trunc_ln44_21_fu_201_p4 : STD_LOGIC_VECTOR (36 downto 0);
    signal select_ln51_23_fu_425_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_22_fu_419_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_21_fu_413_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_20_fu_407_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_19_fu_401_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_18_fu_395_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_17_fu_389_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_16_fu_383_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_15_fu_377_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_fu_371_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((layer18_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                icmp_ln51_15_reg_466 <= icmp_ln51_15_fu_227_p2;
                icmp_ln51_16_reg_476 <= icmp_ln51_16_fu_243_p2;
                icmp_ln51_17_reg_486 <= icmp_ln51_17_fu_259_p2;
                icmp_ln51_18_reg_496 <= icmp_ln51_18_fu_275_p2;
                icmp_ln51_19_reg_506 <= icmp_ln51_19_fu_291_p2;
                icmp_ln51_20_reg_516 <= icmp_ln51_20_fu_307_p2;
                icmp_ln51_21_reg_526 <= icmp_ln51_21_fu_323_p2;
                icmp_ln51_22_reg_536 <= icmp_ln51_22_fu_339_p2;
                icmp_ln51_23_reg_546 <= icmp_ln51_23_fu_355_p2;
                icmp_ln51_reg_456 <= icmp_ln51_fu_211_p2;
                out_data_22_reg_471 <= layer17_out_dout(62 downto 47);
                out_data_23_reg_481 <= layer17_out_dout(99 downto 84);
                out_data_24_reg_491 <= layer17_out_dout(136 downto 121);
                out_data_reg_461 <= layer17_out_dout(25 downto 10);
                trunc_ln4_reg_501 <= layer17_out_dout(173 downto 158);
                trunc_ln52_1_reg_521 <= layer17_out_dout(247 downto 232);
                trunc_ln52_2_reg_531 <= layer17_out_dout(284 downto 269);
                trunc_ln52_3_reg_541 <= layer17_out_dout(321 downto 306);
                trunc_ln52_4_reg_551 <= layer17_out_dout(358 downto 343);
                trunc_ln52_s_reg_511 <= layer17_out_dout(210 downto 195);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, layer18_out_full_n, ap_CS_fsm_state2, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((layer18_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(layer18_out_full_n)
    begin
        if ((layer18_out_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, layer17_out_empty_n)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (layer17_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, layer18_out_full_n, ap_CS_fsm_state2)
    begin
        if (((layer18_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    icmp_ln51_15_fu_227_p2 <= "1" when (signed(trunc_ln44_s_fu_121_p4) > signed(ap_const_lv37_0)) else "0";
    icmp_ln51_16_fu_243_p2 <= "1" when (signed(trunc_ln44_14_fu_131_p4) > signed(ap_const_lv37_0)) else "0";
    icmp_ln51_17_fu_259_p2 <= "1" when (signed(trunc_ln44_15_fu_141_p4) > signed(ap_const_lv37_0)) else "0";
    icmp_ln51_18_fu_275_p2 <= "1" when (signed(trunc_ln44_16_fu_151_p4) > signed(ap_const_lv37_0)) else "0";
    icmp_ln51_19_fu_291_p2 <= "1" when (signed(trunc_ln44_17_fu_161_p4) > signed(ap_const_lv37_0)) else "0";
    icmp_ln51_20_fu_307_p2 <= "1" when (signed(trunc_ln44_18_fu_171_p4) > signed(ap_const_lv37_0)) else "0";
    icmp_ln51_21_fu_323_p2 <= "1" when (signed(trunc_ln44_19_fu_181_p4) > signed(ap_const_lv37_0)) else "0";
    icmp_ln51_22_fu_339_p2 <= "1" when (signed(trunc_ln44_20_fu_191_p4) > signed(ap_const_lv37_0)) else "0";
    icmp_ln51_23_fu_355_p2 <= "1" when (signed(trunc_ln44_21_fu_201_p4) > signed(ap_const_lv37_0)) else "0";
    icmp_ln51_fu_211_p2 <= "1" when (signed(trunc_ln44_fu_117_p1) > signed(ap_const_lv37_0)) else "0";

    internal_ap_ready_assign_proc : process(layer18_out_full_n, ap_CS_fsm_state2)
    begin
        if (((layer18_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    layer17_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, layer17_out_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer17_out_blk_n <= layer17_out_empty_n;
        else 
            layer17_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer17_out_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer17_out_read <= ap_const_logic_1;
        else 
            layer17_out_read <= ap_const_logic_0;
        end if; 
    end process;


    layer18_out_blk_n_assign_proc : process(layer18_out_full_n, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            layer18_out_blk_n <= layer18_out_full_n;
        else 
            layer18_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer18_out_din <= (((((((((select_ln51_23_fu_425_p3 & select_ln51_22_fu_419_p3) & select_ln51_21_fu_413_p3) & select_ln51_20_fu_407_p3) & select_ln51_19_fu_401_p3) & select_ln51_18_fu_395_p3) & select_ln51_17_fu_389_p3) & select_ln51_16_fu_383_p3) & select_ln51_15_fu_377_p3) & select_ln51_fu_371_p3);

    layer18_out_write_assign_proc : process(layer18_out_full_n, ap_CS_fsm_state2)
    begin
        if (((layer18_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            layer18_out_write <= ap_const_logic_1;
        else 
            layer18_out_write <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    select_ln51_15_fu_377_p3 <= 
        out_data_22_reg_471 when (icmp_ln51_15_reg_466(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_16_fu_383_p3 <= 
        out_data_23_reg_481 when (icmp_ln51_16_reg_476(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_17_fu_389_p3 <= 
        out_data_24_reg_491 when (icmp_ln51_17_reg_486(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_18_fu_395_p3 <= 
        trunc_ln4_reg_501 when (icmp_ln51_18_reg_496(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_19_fu_401_p3 <= 
        trunc_ln52_s_reg_511 when (icmp_ln51_19_reg_506(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_20_fu_407_p3 <= 
        trunc_ln52_1_reg_521 when (icmp_ln51_20_reg_516(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_21_fu_413_p3 <= 
        trunc_ln52_2_reg_531 when (icmp_ln51_21_reg_526(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_22_fu_419_p3 <= 
        trunc_ln52_3_reg_541 when (icmp_ln51_22_reg_536(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_23_fu_425_p3 <= 
        trunc_ln52_4_reg_551 when (icmp_ln51_23_reg_546(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_fu_371_p3 <= 
        out_data_reg_461 when (icmp_ln51_reg_456(0) = '1') else 
        ap_const_lv16_0;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln44_14_fu_131_p4 <= layer17_out_dout(110 downto 74);
    trunc_ln44_15_fu_141_p4 <= layer17_out_dout(147 downto 111);
    trunc_ln44_16_fu_151_p4 <= layer17_out_dout(184 downto 148);
    trunc_ln44_17_fu_161_p4 <= layer17_out_dout(221 downto 185);
    trunc_ln44_18_fu_171_p4 <= layer17_out_dout(258 downto 222);
    trunc_ln44_19_fu_181_p4 <= layer17_out_dout(295 downto 259);
    trunc_ln44_20_fu_191_p4 <= layer17_out_dout(332 downto 296);
    trunc_ln44_21_fu_201_p4 <= layer17_out_dout(369 downto 333);
    trunc_ln44_fu_117_p1 <= layer17_out_dout(37 - 1 downto 0);
    trunc_ln44_s_fu_121_p4 <= layer17_out_dout(73 downto 37);
end behav;
