// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module gaussian_thresholded_relu_array_ap_fixed_array_ap_fixed_6u_thresholdedrelu_config4_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer2_out_dout,
        layer2_out_num_data_valid,
        layer2_out_fifo_cap,
        layer2_out_empty_n,
        layer2_out_read,
        layer4_out_din,
        layer4_out_num_data_valid,
        layer4_out_fifo_cap,
        layer4_out_full_n,
        layer4_out_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [221:0] layer2_out_dout;
input  [12:0] layer2_out_num_data_valid;
input  [12:0] layer2_out_fifo_cap;
input   layer2_out_empty_n;
output   layer2_out_read;
output  [95:0] layer4_out_din;
input  [12:0] layer4_out_num_data_valid;
input  [12:0] layer4_out_fifo_cap;
input   layer4_out_full_n;
output   layer4_out_write;
output   start_out;
output   start_write;

reg ap_idle;
reg layer2_out_read;
reg layer4_out_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln528_fu_115_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer2_out_blk_n;
wire    ap_block_pp0_stage0;
reg    layer4_out_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln538_fu_186_p2;
reg   [0:0] icmp_ln538_reg_346;
reg   [15:0] out_data_reg_351;
wire   [0:0] icmp_ln538_8_fu_202_p2;
reg   [0:0] icmp_ln538_8_reg_356;
reg   [15:0] out_data_9_reg_361;
wire   [0:0] icmp_ln538_9_fu_218_p2;
reg   [0:0] icmp_ln538_9_reg_366;
reg   [15:0] out_data_11_reg_371;
wire   [0:0] icmp_ln538_10_fu_234_p2;
reg   [0:0] icmp_ln538_10_reg_376;
reg   [15:0] out_data_13_reg_381;
wire   [0:0] icmp_ln538_11_fu_250_p2;
reg   [0:0] icmp_ln538_11_reg_386;
reg   [15:0] trunc_ln2_reg_391;
wire   [0:0] icmp_ln538_12_fu_266_p2;
reg   [0:0] icmp_ln538_12_reg_396;
reg   [15:0] trunc_ln539_9_reg_401;
reg   [11:0] i_fu_90;
wire   [11:0] i_4_fu_121_p2;
wire    ap_loop_init;
reg   [11:0] ap_sig_allocacmp_i_3;
reg    ap_block_pp0_stage0_01001;
wire   [36:0] trunc_ln531_fu_132_p1;
wire   [36:0] trunc_ln531_s_fu_136_p4;
wire   [36:0] trunc_ln531_7_fu_146_p4;
wire   [36:0] trunc_ln531_8_fu_156_p4;
wire   [36:0] trunc_ln531_9_fu_166_p4;
wire   [36:0] trunc_ln531_1_fu_176_p4;
wire   [15:0] select_ln538_9_fu_312_p3;
wire   [15:0] select_ln538_fu_306_p3;
wire   [15:0] out_data_14_fu_300_p3;
wire   [15:0] out_data_12_fu_294_p3;
wire   [15:0] out_data_10_fu_288_p3;
wire   [15:0] out_data_8_fu_282_p3;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_137;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 i_fu_90 = 12'd0;
end

gaussian_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_137)) begin
        if ((icmp_ln528_fu_115_p2 == 1'd0)) begin
            i_fu_90 <= i_4_fu_121_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_90 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln538_10_reg_376 <= icmp_ln538_10_fu_234_p2;
        icmp_ln538_11_reg_386 <= icmp_ln538_11_fu_250_p2;
        icmp_ln538_12_reg_396 <= icmp_ln538_12_fu_266_p2;
        icmp_ln538_8_reg_356 <= icmp_ln538_8_fu_202_p2;
        icmp_ln538_9_reg_366 <= icmp_ln538_9_fu_218_p2;
        icmp_ln538_reg_346 <= icmp_ln538_fu_186_p2;
        out_data_11_reg_371 <= {{layer2_out_dout[99:84]}};
        out_data_13_reg_381 <= {{layer2_out_dout[136:121]}};
        out_data_9_reg_361 <= {{layer2_out_dout[62:47]}};
        out_data_reg_351 <= {{layer2_out_dout[25:10]}};
        trunc_ln2_reg_391 <= {{layer2_out_dout[173:158]}};
        trunc_ln539_9_reg_401 <= {{layer2_out_dout[210:195]}};
    end
end

always @ (*) begin
    if (((icmp_ln528_fu_115_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_3 = 12'd0;
    end else begin
        ap_sig_allocacmp_i_3 = i_fu_90;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer2_out_blk_n = layer2_out_empty_n;
    end else begin
        layer2_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer2_out_read = 1'b1;
    end else begin
        layer2_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer4_out_blk_n = layer4_out_full_n;
    end else begin
        layer4_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer4_out_write = 1'b1;
    end else begin
        layer4_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (layer2_out_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (layer4_out_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_137 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign i_4_fu_121_p2 = (ap_sig_allocacmp_i_3 + 12'd1);

assign icmp_ln528_fu_115_p2 = ((ap_sig_allocacmp_i_3 == 12'd2116) ? 1'b1 : 1'b0);

assign icmp_ln538_10_fu_234_p2 = (($signed(trunc_ln531_8_fu_156_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_11_fu_250_p2 = (($signed(trunc_ln531_9_fu_166_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_12_fu_266_p2 = (($signed(trunc_ln531_1_fu_176_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_8_fu_202_p2 = (($signed(trunc_ln531_s_fu_136_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_9_fu_218_p2 = (($signed(trunc_ln531_7_fu_146_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_fu_186_p2 = (($signed(trunc_ln531_fu_132_p1) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign layer4_out_din = {{{{{{select_ln538_9_fu_312_p3}, {select_ln538_fu_306_p3}}, {out_data_14_fu_300_p3}}, {out_data_12_fu_294_p3}}, {out_data_10_fu_288_p3}}, {out_data_8_fu_282_p3}};

assign out_data_10_fu_288_p3 = ((icmp_ln538_8_reg_356[0:0] == 1'b1) ? out_data_9_reg_361 : 16'd0);

assign out_data_12_fu_294_p3 = ((icmp_ln538_9_reg_366[0:0] == 1'b1) ? out_data_11_reg_371 : 16'd0);

assign out_data_14_fu_300_p3 = ((icmp_ln538_10_reg_376[0:0] == 1'b1) ? out_data_13_reg_381 : 16'd0);

assign out_data_8_fu_282_p3 = ((icmp_ln538_reg_346[0:0] == 1'b1) ? out_data_reg_351 : 16'd0);

assign select_ln538_9_fu_312_p3 = ((icmp_ln538_12_reg_396[0:0] == 1'b1) ? trunc_ln539_9_reg_401 : 16'd0);

assign select_ln538_fu_306_p3 = ((icmp_ln538_11_reg_386[0:0] == 1'b1) ? trunc_ln2_reg_391 : 16'd0);

assign start_out = real_start;

assign trunc_ln531_1_fu_176_p4 = {{layer2_out_dout[221:185]}};

assign trunc_ln531_7_fu_146_p4 = {{layer2_out_dout[110:74]}};

assign trunc_ln531_8_fu_156_p4 = {{layer2_out_dout[147:111]}};

assign trunc_ln531_9_fu_166_p4 = {{layer2_out_dout[184:148]}};

assign trunc_ln531_fu_132_p1 = layer2_out_dout[36:0];

assign trunc_ln531_s_fu_136_p4 = {{layer2_out_dout[73:37]}};

endmodule //gaussian_thresholded_relu_array_ap_fixed_array_ap_fixed_6u_thresholdedrelu_config4_s
