// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module gaussian_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_40_20_5_3_0_10u_config10_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer9_out_dout,
        layer9_out_num_data_valid,
        layer9_out_fifo_cap,
        layer9_out_empty_n,
        layer9_out_read,
        start_out,
        start_write,
        layer10_out_din,
        layer10_out_num_data_valid,
        layer10_out_fifo_cap,
        layer10_out_full_n,
        layer10_out_write
);

parameter    ap_ST_fsm_pp0_stage0 = 9'd1;
parameter    ap_ST_fsm_pp0_stage1 = 9'd2;
parameter    ap_ST_fsm_pp0_stage2 = 9'd4;
parameter    ap_ST_fsm_pp0_stage3 = 9'd8;
parameter    ap_ST_fsm_pp0_stage4 = 9'd16;
parameter    ap_ST_fsm_pp0_stage5 = 9'd32;
parameter    ap_ST_fsm_pp0_stage6 = 9'd64;
parameter    ap_ST_fsm_pp0_stage7 = 9'd128;
parameter    ap_ST_fsm_pp0_stage8 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [127:0] layer9_out_dout;
input  [4:0] layer9_out_num_data_valid;
input  [4:0] layer9_out_fifo_cap;
input   layer9_out_empty_n;
output   layer9_out_read;
output   start_out;
output   start_write;
output  [399:0] layer10_out_din;
input  [2:0] layer10_out_num_data_valid;
input  [2:0] layer10_out_fifo_cap;
input   layer10_out_full_n;
output   layer10_out_write;

reg ap_idle;
reg layer9_out_read;
reg start_write;
reg layer10_out_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    internal_ap_ready;
wire    ap_CS_fsm_pp0_stage1;
reg   [0:0] icmp_ln25_reg_572;
reg    ap_block_state2_pp0_stage1_iter0;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_layer10_out_blk_n;
reg    ap_block_state11_pp0_stage1_iter1;
reg    ap_block_pp0_stage1_subdone;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage8;
wire    ap_block_pp0_stage8_subdone;
reg    layer9_out_blk_n;
wire    ap_block_pp0_stage1;
reg    layer10_out_blk_n;
wire   [0:0] icmp_ln25_fu_466_p2;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_11001;
reg    ap_enable_reg_pp0_iter0_reg;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_ap_start;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_ap_done;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_ap_idle;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_ap_ready;
reg    grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_ap_ce;
wire   [15:0] grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_p_read;
wire   [15:0] grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_p_read1;
wire   [15:0] grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_p_read2;
wire   [15:0] grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_p_read3;
wire   [15:0] grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_p_read4;
wire   [15:0] grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_p_read5;
wire   [15:0] grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_p_read6;
wire   [15:0] grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_p_read7;
wire   [399:0] grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_layer10_out_din;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_layer10_out_write;
reg    ap_block_state2_pp0_stage1_iter0_ignore_call12;
reg    ap_block_pp0_stage1_11001_ignoreCallOp33;
reg    ap_block_pp0_stage2_11001_ignoreCallOp34;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage3_11001_ignoreCallOp35;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage4_11001_ignoreCallOp36;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage5_11001_ignoreCallOp37;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage6_11001_ignoreCallOp38;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage7_11001_ignoreCallOp39;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_pp0_stage8_11001_ignoreCallOp40;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call12;
reg    ap_block_pp0_stage0_11001_ignoreCallOp41;
reg    grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_ap_start_reg;
reg    ap_block_pp0_stage1_11001;
wire    ap_block_pp0_stage3;
wire    ap_block_pp0_stage2;
wire    ap_block_pp0_stage4;
wire    ap_block_pp0_stage5;
reg    ap_block_pp0_stage2_11001;
wire    ap_block_pp0_stage3_11001;
reg   [4:0] indvar_flatten_fu_250;
wire   [4:0] add_ln25_fu_472_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_indvar_flatten_load;
wire    ap_block_pp0_stage0;
wire    ap_continue_int;
reg    ap_done_int;
reg   [8:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
reg    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage6_subdone;
wire    ap_block_pp0_stage7_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_234;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 9'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_ap_start_reg = 1'b0;
#0 indvar_flatten_fu_250 = 5'd0;
end

gaussian_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_ap_start),
    .ap_done(grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_ap_done),
    .ap_idle(grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_ap_idle),
    .ap_ready(grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_ap_ready),
    .ap_ce(grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_ap_ce),
    .p_read(grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_p_read),
    .p_read1(grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_p_read1),
    .p_read2(grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_p_read2),
    .p_read3(grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_p_read3),
    .p_read4(grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_p_read4),
    .p_read5(grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_p_read5),
    .p_read6(grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_p_read6),
    .p_read7(grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_p_read7),
    .layer10_out_din(grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_layer10_out_din),
    .layer10_out_num_data_valid(3'd0),
    .layer10_out_fifo_cap(3'd0),
    .layer10_out_full_n(layer10_out_full_n),
    .layer10_out_write(grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_layer10_out_write),
    .layer10_out_blk_n(grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_layer10_out_blk_n)
);

gaussian_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage8_subdone) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln25_fu_466_p2 == 1'd0))) begin
            grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_ap_start_reg <= 1'b1;
        end else if ((grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_ap_ready == 1'b1)) begin
            grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_234)) begin
        if ((icmp_ln25_fu_466_p2 == 1'd0)) begin
            indvar_flatten_fu_250 <= add_ln25_fu_472_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_250 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln25_reg_572 <= icmp_ln25_fu_466_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (icmp_ln25_reg_572 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage8_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 5'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_250;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp41) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage8_11001_ignoreCallOp40) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage7_11001_ignoreCallOp39) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001_ignoreCallOp38) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001_ignoreCallOp37) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001_ignoreCallOp36) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001_ignoreCallOp35) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001_ignoreCallOp34) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001_ignoreCallOp33) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_ap_ce = 1'b1;
    end else begin
        grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        layer10_out_blk_n = grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_layer10_out_blk_n;
    end else begin
        layer10_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        layer10_out_write = grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_layer10_out_write;
    end else begin
        layer10_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (icmp_ln25_reg_572 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        layer9_out_blk_n = layer9_out_empty_n;
    end else begin
        layer9_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln25_reg_572 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        layer9_out_read = 1'b1;
    end else begin
        layer9_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_pp0_stage8 : begin
            if ((1'b0 == ap_block_pp0_stage8_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln25_fu_472_p2 = (ap_sig_allocacmp_indvar_flatten_load + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage8 = ap_CS_fsm[32'd8];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp41 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_ignore_call12));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage1_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_ignoreCallOp33 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0_ignore_call12));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage1_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0)));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_pp0_stage2_11001_ignoreCallOp34 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = (ap_done_reg == 1'b1);
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001_ignoreCallOp35 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001_ignoreCallOp36 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001_ignoreCallOp37 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001_ignoreCallOp38 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001_ignoreCallOp39 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_11001_ignoreCallOp40 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state11_pp0_stage1_iter1 = (grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_layer10_out_blk_n == 1'b0);
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call12 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = ((icmp_ln25_reg_572 == 1'd0) & (layer9_out_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0_ignore_call12 = ((icmp_ln25_reg_572 == 1'd0) & (layer9_out_empty_n == 1'b0));
end

always @ (*) begin
    ap_condition_234 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = internal_ap_ready;

assign grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_ap_start = grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_ap_start_reg;

assign grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_p_read = layer9_out_dout[15:0];

assign grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_p_read1 = {{layer9_out_dout[31:16]}};

assign grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_p_read2 = {{layer9_out_dout[47:32]}};

assign grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_p_read3 = {{layer9_out_dout[63:48]}};

assign grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_p_read4 = {{layer9_out_dout[79:64]}};

assign grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_p_read5 = {{layer9_out_dout[95:80]}};

assign grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_p_read6 = {{layer9_out_dout[111:96]}};

assign grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_p_read7 = {{layer9_out_dout[127:112]}};

assign icmp_ln25_fu_466_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 5'd16) ? 1'b1 : 1'b0);

assign layer10_out_din = grp_compute_output_buffer_2d_array_array_ap_fixed_40_20_5_3_0_10u_config10_s_fu_260_layer10_out_din;

assign start_out = real_start;

endmodule //gaussian_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_40_20_5_3_0_10u_config10_s
