// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module gaussian_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config2_mult_s (
        ap_clk,
        ap_rst,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_28,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_27,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_26,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_25,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_24,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_23,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_22,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_21,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_20,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_28;
input  [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_27;
input  [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_26;
input  [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_25;
input  [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_24;
input  [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_23;
input  [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_22;
input  [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_21;
input  [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_20;
output  [36:0] ap_return_0;
output  [36:0] ap_return_1;
output  [36:0] ap_return_2;
output  [36:0] ap_return_3;
output  [36:0] ap_return_4;
output  [36:0] ap_return_5;
input   ap_ce;

reg[36:0] ap_return_0;
reg[36:0] ap_return_1;
reg[36:0] ap_return_2;
reg[36:0] ap_return_3;
reg[36:0] ap_return_4;
reg[36:0] ap_return_5;

wire   [23:0] mul_ln73_603_fu_199_p2;
reg   [23:0] mul_ln73_603_reg_2200;
wire    ap_block_pp0_stage0_11001;
wire   [24:0] mul_ln73_606_fu_194_p2;
reg   [24:0] mul_ln73_606_reg_2204;
wire   [24:0] mul_ln73_607_fu_186_p2;
reg   [24:0] mul_ln73_607_reg_2208;
wire   [22:0] mul_ln73_608_fu_178_p2;
reg   [22:0] mul_ln73_608_reg_2212;
wire   [23:0] mul_ln73_609_fu_183_p2;
reg   [23:0] mul_ln73_609_reg_2216;
wire   [23:0] mul_ln73_610_fu_176_p2;
reg   [23:0] mul_ln73_610_reg_2220;
wire   [21:0] mul_ln73_611_fu_169_p2;
reg   [21:0] mul_ln73_611_reg_2224;
wire   [25:0] mul_ln73_612_fu_187_p2;
reg   [25:0] mul_ln73_612_reg_2228;
wire   [25:0] mul_ln73_613_fu_212_p2;
reg   [25:0] mul_ln73_613_reg_2232;
wire   [24:0] mul_ln73_fu_182_p2;
reg   [24:0] mul_ln73_reg_7572;
wire   [24:0] mul_ln73_604_fu_173_p2;
reg   [24:0] mul_ln73_604_reg_7576;
wire   [25:0] mul_ln73_605_fu_193_p2;
reg   [25:0] mul_ln73_605_reg_7580;
wire   [25:0] mul_ln73_614_fu_209_p2;
reg   [25:0] mul_ln73_614_reg_7584;
wire   [25:0] mul_ln73_615_fu_202_p2;
reg   [25:0] mul_ln73_615_reg_7588;
wire   [25:0] mul_ln73_616_fu_218_p2;
reg   [25:0] mul_ln73_616_reg_7592;
wire   [24:0] mul_ln73_618_fu_207_p2;
reg   [24:0] mul_ln73_618_reg_7596;
wire   [25:0] mul_ln73_619_fu_180_p2;
reg   [25:0] mul_ln73_619_reg_7600;
wire   [23:0] mul_ln73_620_fu_172_p2;
reg   [23:0] mul_ln73_620_reg_7604;
wire   [25:0] mul_ln73_621_fu_167_p2;
reg   [25:0] mul_ln73_621_reg_7608;
wire   [24:0] mul_ln73_622_fu_201_p2;
reg   [24:0] mul_ln73_622_reg_7612;
wire   [24:0] mul_ln73_623_fu_204_p2;
reg   [24:0] mul_ln73_623_reg_7616;
wire   [25:0] mul_ln73_624_fu_166_p2;
reg   [25:0] mul_ln73_624_reg_7620;
wire   [24:0] mul_ln73_625_fu_168_p2;
reg   [24:0] mul_ln73_625_reg_7624;
wire   [22:0] mul_ln73_627_fu_189_p2;
reg   [22:0] mul_ln73_627_reg_7628;
wire   [25:0] mul_ln73_628_fu_219_p2;
reg   [25:0] mul_ln73_628_reg_7632;
wire   [26:0] mul_ln73_629_fu_185_p2;
reg   [26:0] mul_ln73_629_reg_7636;
wire   [24:0] mul_ln73_631_fu_206_p2;
reg   [24:0] mul_ln73_631_reg_7640;
wire   [23:0] mul_ln73_632_fu_171_p2;
reg   [23:0] mul_ln73_632_reg_7644;
wire   [25:0] mul_ln73_634_fu_203_p2;
reg   [25:0] mul_ln73_634_reg_7648;
wire   [24:0] mul_ln73_635_fu_188_p2;
reg   [24:0] mul_ln73_635_reg_7652;
wire   [25:0] mul_ln73_636_fu_190_p2;
reg   [25:0] mul_ln73_636_reg_7656;
wire   [25:0] mul_ln73_637_fu_196_p2;
reg   [25:0] mul_ln73_637_reg_7660;
wire   [23:0] mul_ln73_640_fu_211_p2;
reg   [23:0] mul_ln73_640_reg_7664;
wire   [23:0] mul_ln73_641_fu_175_p2;
reg   [23:0] mul_ln73_641_reg_7668;
wire   [25:0] mul_ln73_642_fu_197_p2;
reg   [25:0] mul_ln73_642_reg_7672;
wire   [24:0] mul_ln73_644_fu_177_p2;
reg   [24:0] mul_ln73_644_reg_7676;
wire   [23:0] mul_ln73_647_fu_184_p2;
reg   [23:0] mul_ln73_647_reg_7680;
wire   [25:0] mul_ln73_648_fu_215_p2;
reg   [25:0] mul_ln73_648_reg_7684;
wire   [24:0] mul_ln73_617_fu_198_p2;
reg   [24:0] mul_ln73_617_reg_8300;
wire   [24:0] mul_ln73_626_fu_216_p2;
reg   [24:0] mul_ln73_626_reg_8304;
wire   [25:0] mul_ln73_630_fu_174_p2;
reg   [25:0] mul_ln73_630_reg_8308;
wire   [25:0] mul_ln73_633_fu_210_p2;
reg   [25:0] mul_ln73_633_reg_8312;
wire   [26:0] mul_ln73_638_fu_213_p2;
reg   [26:0] mul_ln73_638_reg_8316;
wire   [24:0] mul_ln73_639_fu_195_p2;
reg   [24:0] mul_ln73_639_reg_8320;
wire   [26:0] mul_ln73_643_fu_217_p2;
reg   [26:0] mul_ln73_643_reg_8324;
wire   [24:0] mul_ln73_645_fu_170_p2;
reg   [24:0] mul_ln73_645_reg_8328;
wire   [26:0] mul_ln73_646_fu_205_p2;
reg   [26:0] mul_ln73_646_reg_8332;
reg  signed [15:0] a_reg_9256;
wire  signed [24:0] sext_ln73_350_fu_8346_p1;
reg  signed [24:0] sext_ln73_350_reg_9261;
wire  signed [24:0] sext_ln70_282_fu_8390_p1;
reg  signed [24:0] sext_ln70_282_reg_9267;
wire  signed [24:0] sext_ln70_290_fu_8515_p1;
reg  signed [24:0] sext_ln70_290_reg_9272;
reg  signed [15:0] a_58_reg_9277;
reg  signed [15:0] a_59_reg_9284;
reg  signed [15:0] a_60_reg_9292;
reg  signed [15:0] a_61_reg_9298;
wire  signed [24:0] sext_ln70_301_fu_8580_p1;
reg  signed [24:0] sext_ln70_301_reg_9303;
wire   [22:0] add_ln58_773_fu_8620_p2;
reg   [22:0] add_ln58_773_reg_9308;
wire   [24:0] add_ln58_775_fu_8626_p2;
reg   [24:0] add_ln58_775_reg_9313;
wire   [25:0] add_ln58_776_fu_8632_p2;
reg   [25:0] add_ln58_776_reg_9318;
wire   [25:0] add_ln58_777_fu_8638_p2;
reg   [25:0] add_ln58_777_reg_9323;
wire   [23:0] add_ln58_780_fu_8644_p2;
reg   [23:0] add_ln58_780_reg_9328;
wire   [21:0] add_ln58_783_fu_8650_p2;
reg   [21:0] add_ln58_783_reg_9333;
wire   [22:0] add_ln58_787_fu_8656_p2;
reg   [22:0] add_ln58_787_reg_9338;
wire   [25:0] add_ln58_785_fu_8876_p2;
reg   [25:0] add_ln58_785_reg_9343;
wire   [26:0] add_ln58_790_fu_8911_p2;
reg   [26:0] add_ln58_790_reg_9348;
wire   [26:0] add_ln58_796_fu_8959_p2;
reg   [26:0] add_ln58_796_reg_9353;
wire   [26:0] add_ln58_799_fu_8981_p2;
reg   [26:0] add_ln58_799_reg_9358;
wire   [24:0] add_ln58_802_fu_8997_p2;
reg   [24:0] add_ln58_802_reg_9363;
wire   [24:0] add_ln58_806_fu_9003_p2;
reg   [24:0] add_ln58_806_reg_9368;
wire   [26:0] add_ln58_812_fu_9009_p2;
reg   [26:0] add_ln58_812_reg_9373;
wire   [24:0] add_ln58_816_fu_9035_p2;
reg   [24:0] add_ln58_816_reg_9378;
wire   [27:0] add_ln58_821_fu_9063_p2;
reg   [27:0] add_ln58_821_reg_9383;
wire  signed [15:0] mul_ln73_624_fu_166_p0;
wire  signed [25:0] sext_ln70_289_fu_8509_p1;
wire   [9:0] mul_ln73_624_fu_166_p1;
wire    ap_block_pp0_stage0;
wire  signed [15:0] mul_ln73_621_fu_167_p0;
wire  signed [25:0] sext_ln70_287_fu_8442_p1;
wire  signed [9:0] mul_ln73_621_fu_167_p1;
wire  signed [15:0] mul_ln73_625_fu_168_p0;
wire   [8:0] mul_ln73_625_fu_168_p1;
wire  signed [6:0] mul_ln73_611_fu_169_p1;
wire  signed [15:0] mul_ln73_645_fu_170_p0;
wire   [8:0] mul_ln73_645_fu_170_p1;
wire  signed [7:0] mul_ln73_632_fu_171_p1;
wire  signed [7:0] mul_ln73_620_fu_172_p1;
wire  signed [15:0] mul_ln73_604_fu_173_p0;
wire   [9:0] mul_ln73_604_fu_173_p1;
wire  signed [15:0] mul_ln73_630_fu_174_p0;
wire  signed [25:0] sext_ln70_293_fu_8674_p1;
wire  signed [9:0] mul_ln73_630_fu_174_p1;
wire  signed [15:0] mul_ln73_641_fu_175_p0;
wire  signed [23:0] sext_ln70_297_fu_8559_p1;
wire   [7:0] mul_ln73_641_fu_175_p1;
wire  signed [15:0] mul_ln73_610_fu_176_p0;
wire  signed [23:0] sext_ln70_281_fu_8367_p1;
wire   [7:0] mul_ln73_610_fu_176_p1;
wire  signed [9:0] mul_ln73_644_fu_177_p1;
wire  signed [7:0] mul_ln73_608_fu_178_p1;
wire  signed [15:0] mul_ln73_619_fu_180_p0;
wire  signed [9:0] mul_ln73_619_fu_180_p1;
wire  signed [15:0] mul_ln73_fu_182_p0;
wire  signed [9:0] mul_ln73_fu_182_p1;
wire  signed [15:0] mul_ln73_609_fu_183_p0;
wire   [7:0] mul_ln73_609_fu_183_p1;
wire  signed [7:0] mul_ln73_647_fu_184_p1;
wire  signed [10:0] mul_ln73_629_fu_185_p1;
wire  signed [15:0] mul_ln73_607_fu_186_p0;
wire  signed [9:0] mul_ln73_607_fu_186_p1;
wire  signed [15:0] mul_ln73_612_fu_187_p0;
wire  signed [25:0] sext_ln70_fu_8356_p1;
wire  signed [9:0] mul_ln73_612_fu_187_p1;
wire   [8:0] mul_ln73_635_fu_188_p1;
wire  signed [6:0] mul_ln73_627_fu_189_p1;
wire  signed [15:0] mul_ln73_636_fu_190_p0;
wire  signed [25:0] sext_ln70_296_fu_8549_p1;
wire  signed [9:0] mul_ln73_636_fu_190_p1;
wire   [10:0] mul_ln73_605_fu_193_p1;
wire  signed [15:0] mul_ln73_606_fu_194_p0;
wire  signed [9:0] mul_ln73_606_fu_194_p1;
wire   [9:0] mul_ln73_639_fu_195_p1;
wire  signed [15:0] mul_ln73_637_fu_196_p0;
wire  signed [25:0] sext_ln70_299_fu_8565_p1;
wire   [9:0] mul_ln73_637_fu_196_p1;
wire  signed [15:0] mul_ln73_642_fu_197_p0;
wire  signed [9:0] mul_ln73_642_fu_197_p1;
wire  signed [15:0] mul_ln73_617_fu_198_p0;
wire  signed [8:0] mul_ln73_617_fu_198_p1;
wire   [8:0] mul_ln73_603_fu_199_p1;
wire  signed [8:0] mul_ln73_622_fu_201_p1;
wire  signed [15:0] mul_ln73_615_fu_202_p0;
wire  signed [25:0] sext_ln70_283_fu_8395_p1;
wire   [9:0] mul_ln73_615_fu_202_p1;
wire  signed [15:0] mul_ln73_634_fu_203_p0;
wire   [9:0] mul_ln73_634_fu_203_p1;
wire  signed [15:0] mul_ln73_623_fu_204_p0;
wire   [8:0] mul_ln73_623_fu_204_p1;
wire  signed [15:0] mul_ln73_646_fu_205_p0;
wire  signed [26:0] sext_ln70_303_fu_8791_p1;
wire  signed [10:0] mul_ln73_646_fu_205_p1;
wire   [8:0] mul_ln73_631_fu_206_p1;
wire   [8:0] mul_ln73_618_fu_207_p1;
wire  signed [15:0] mul_ln73_614_fu_209_p0;
wire  signed [10:0] mul_ln73_614_fu_209_p1;
wire  signed [15:0] mul_ln73_633_fu_210_p0;
wire  signed [9:0] mul_ln73_633_fu_210_p1;
wire  signed [15:0] mul_ln73_640_fu_211_p0;
wire   [8:0] mul_ln73_640_fu_211_p1;
wire  signed [15:0] mul_ln73_613_fu_212_p0;
wire   [9:0] mul_ln73_613_fu_212_p1;
wire  signed [10:0] mul_ln73_638_fu_213_p1;
wire  signed [9:0] mul_ln73_648_fu_215_p1;
wire  signed [15:0] mul_ln73_626_fu_216_p0;
wire  signed [8:0] mul_ln73_626_fu_216_p1;
wire  signed [15:0] mul_ln73_643_fu_217_p0;
wire  signed [10:0] mul_ln73_643_fu_217_p1;
wire  signed [15:0] mul_ln73_616_fu_218_p0;
wire   [9:0] mul_ln73_616_fu_218_p1;
wire  signed [15:0] mul_ln73_628_fu_219_p0;
wire  signed [9:0] mul_ln73_628_fu_219_p1;
wire  signed [15:0] sext_ln73_350_fu_8346_p0;
wire  signed [15:0] sext_ln70_fu_8356_p0;
wire  signed [15:0] sext_ln70_281_fu_8367_p0;
wire  signed [15:0] sext_ln70_282_fu_8390_p0;
wire  signed [15:0] sext_ln70_283_fu_8395_p0;
wire  signed [15:0] sext_ln70_284_fu_8402_p0;
wire  signed [15:0] shl_ln_fu_8406_p1;
wire   [20:0] shl_ln_fu_8406_p3;
wire  signed [21:0] sext_ln73_354_fu_8414_p1;
wire  signed [21:0] sext_ln70_284_fu_8402_p1;
wire   [21:0] sub_ln73_fu_8418_p2;
wire  signed [15:0] sext_ln70_287_fu_8442_p0;
wire  signed [15:0] shl_ln73_s_fu_8448_p1;
wire   [21:0] shl_ln73_s_fu_8448_p3;
wire  signed [15:0] shl_ln73_201_fu_8460_p1;
wire   [18:0] shl_ln73_201_fu_8460_p3;
wire  signed [22:0] sext_ln73_358_fu_8468_p1;
wire  signed [22:0] sext_ln73_357_fu_8456_p1;
wire  signed [15:0] shl_ln73_202_fu_8478_p1;
wire   [20:0] shl_ln73_202_fu_8478_p3;
wire  signed [21:0] sext_ln73_359_fu_8486_p1;
wire   [21:0] sub_ln73_128_fu_8490_p2;
wire  signed [15:0] sext_ln70_289_fu_8509_p0;
wire  signed [15:0] sext_ln70_290_fu_8515_p0;
wire  signed [15:0] sext_ln70_296_fu_8549_p0;
wire  signed [15:0] sext_ln70_297_fu_8559_p0;
wire  signed [15:0] sext_ln70_299_fu_8565_p0;
wire  signed [15:0] sext_ln70_301_fu_8580_p0;
wire   [23:0] add_ln58_fu_8590_p2;
wire   [24:0] add_ln58_771_fu_8600_p2;
wire   [24:0] add_ln58_772_fu_8610_p2;
wire  signed [24:0] sext_ln58_244_fu_8596_p1;
wire  signed [24:0] sext_ln73_353_fu_8382_p1;
wire  signed [25:0] sext_ln58_246_fu_8606_p1;
wire  signed [25:0] sext_ln58_247_fu_8616_p1;
wire  signed [23:0] sext_ln73_360_fu_8496_p1;
wire   [22:0] sub_ln73_127_fu_8472_p2;
wire  signed [22:0] sext_ln73_355_fu_8424_p1;
wire   [23:0] shl_ln73_203_fu_8679_p3;
wire   [19:0] shl_ln73_204_fu_8690_p3;
wire  signed [24:0] sext_ln73_365_fu_8697_p1;
wire  signed [24:0] sext_ln73_364_fu_8686_p1;
wire   [24:0] sub_ln73_129_fu_8701_p2;
wire   [20:0] shl_ln73_205_fu_8711_p3;
wire  signed [16:0] shl_ln73_206_fu_8722_p3;
wire  signed [21:0] sext_ln73_368_fu_8733_p1;
wire  signed [21:0] sext_ln73_366_fu_8718_p1;
wire   [21:0] sub_ln73_130_fu_8737_p2;
wire   [24:0] shl_ln73_207_fu_8747_p3;
wire  signed [25:0] sext_ln73_370_fu_8754_p1;
wire  signed [25:0] sext_ln73_367_fu_8729_p1;
wire   [25:0] sub_ln73_131_fu_8758_p2;
wire   [21:0] shl_ln73_208_fu_8768_p3;
wire   [24:0] add_ln58_770_fu_8796_p2;
wire  signed [24:0] sext_ln58_fu_8806_p1;
wire   [24:0] add_ln58_774_fu_8809_p2;
wire  signed [25:0] sext_ln58_249_fu_8819_p1;
wire   [25:0] add_ln58_778_fu_8828_p2;
wire  signed [25:0] sext_ln58_245_fu_8802_p1;
wire  signed [25:0] sext_ln58_509_fu_8844_p1;
wire   [25:0] add_ln58_779_fu_8838_p2;
wire   [25:0] add_ln58_781_fu_8847_p2;
wire  signed [23:0] sext_ln58_510_fu_8863_p1;
wire   [23:0] add_ln58_784_fu_8866_p2;
wire  signed [25:0] sext_ln58_511_fu_8872_p1;
wire   [25:0] add_ln58_782_fu_8857_p2;
wire  signed [25:0] sext_ln58_248_fu_8815_p1;
wire  signed [25:0] sext_ln73_362_fu_8666_p1;
wire  signed [25:0] sext_ln58_512_fu_8888_p1;
wire   [25:0] add_ln58_786_fu_8882_p2;
wire   [25:0] add_ln58_788_fu_8891_p2;
wire   [25:0] add_ln58_789_fu_8901_p2;
wire  signed [26:0] sext_ln58_513_fu_8907_p1;
wire  signed [26:0] sext_ln58_252_fu_8834_p1;
wire  signed [26:0] sext_ln58_251_fu_8825_p1;
wire  signed [26:0] mul_ln73_1205_cast_i_fu_8670_p1;
wire   [24:0] add_ln58_792_fu_8923_p2;
wire  signed [26:0] sext_ln58_514_fu_8929_p1;
wire   [26:0] add_ln58_791_fu_8917_p2;
wire   [26:0] add_ln58_793_fu_8933_p2;
wire  signed [26:0] sext_ln58_253_fu_8853_p1;
wire  signed [26:0] sext_ln73_371_fu_8764_p1;
wire   [24:0] add_ln58_795_fu_8949_p2;
wire  signed [26:0] sext_ln58_515_fu_8955_p1;
wire   [26:0] add_ln58_794_fu_8943_p2;
wire  signed [26:0] sext_ln58_255_fu_8897_p1;
wire   [25:0] add_ln58_798_fu_8971_p2;
wire  signed [26:0] sext_ln58_516_fu_8977_p1;
wire   [26:0] add_ln58_797_fu_8965_p2;
wire   [23:0] add_ln58_801_fu_8987_p2;
wire  signed [24:0] sext_ln58_517_fu_8993_p1;
wire  signed [24:0] sext_ln73_369_fu_8743_p1;
wire  signed [26:0] sext_ln58_250_fu_8822_p1;
wire  signed [26:0] sext_ln73_361_fu_8662_p1;
wire   [23:0] add_ln58_815_fu_9015_p2;
wire  signed [22:0] sext_ln73_372_fu_8775_p1;
wire   [22:0] sub_ln58_fu_9025_p2;
wire  signed [24:0] sext_ln58_524_fu_9031_p1;
wire  signed [24:0] sext_ln58_523_fu_9021_p1;
wire  signed [27:0] sext_ln58_257_fu_8939_p1;
wire  signed [27:0] mul_ln73_1213_cast_i_fu_8779_p1;
wire  signed [25:0] sub_ln73_271_cast_fu_8707_p1;
wire   [25:0] add_ln58_819_fu_9047_p2;
wire   [25:0] add_ln58_820_fu_9053_p2;
wire  signed [27:0] sext_ln58_526_fu_9059_p1;
wire   [27:0] add_ln58_818_fu_9041_p2;
wire  signed [26:0] sext_ln58_254_fu_9089_p1;
wire  signed [26:0] sext_ln73_363_fu_9073_p1;
wire  signed [26:0] sext_ln58_518_fu_9107_p1;
wire   [26:0] add_ln58_800_fu_9101_p2;
wire   [26:0] add_ln58_803_fu_9110_p2;
wire  signed [27:0] sext_ln58_259_fu_9098_p1;
wire  signed [27:0] sext_ln73_375_fu_9081_p1;
wire   [27:0] add_ln58_804_fu_9120_p2;
wire  signed [27:0] sext_ln58_256_fu_9092_p1;
wire  signed [27:0] sext_ln73_373_fu_9077_p1;
wire  signed [25:0] sext_ln58_519_fu_9136_p1;
wire   [25:0] add_ln58_807_fu_9139_p2;
wire  signed [27:0] sext_ln58_520_fu_9145_p1;
wire   [27:0] add_ln58_805_fu_9130_p2;
wire   [27:0] add_ln58_808_fu_9149_p2;
wire   [24:0] add_ln58_809_fu_9159_p2;
wire  signed [27:0] sext_ln58_521_fu_9165_p1;
wire  signed [27:0] sext_ln58_258_fu_9095_p1;
wire   [27:0] add_ln58_810_fu_9169_p2;
wire  signed [27:0] sext_ln58_260_fu_9116_p1;
wire  signed [27:0] sext_ln73_376_fu_9085_p1;
wire   [27:0] add_ln58_811_fu_9179_p2;
wire  signed [25:0] sext_ln73_356_fu_9069_p1;
wire   [25:0] add_ln58_813_fu_9189_p2;
wire  signed [26:0] sext_ln58_522_fu_9195_p1;
wire  signed [26:0] sext_ln58_525_fu_9204_p1;
wire   [26:0] add_ln58_814_fu_9199_p2;
wire   [26:0] add_ln58_817_fu_9207_p2;
wire  signed [36:0] sext_ln58_261_fu_9126_p1;
wire  signed [36:0] sext_ln58_262_fu_9155_p1;
wire  signed [36:0] sext_ln58_263_fu_9175_p1;
wire  signed [36:0] sext_ln58_264_fu_9185_p1;
wire  signed [36:0] sext_ln58_265_fu_9213_p1;
wire  signed [36:0] sext_ln68_fu_9217_p1;
reg    ap_ce_reg;
reg  signed [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_28_int_reg;
reg  signed [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_27_int_reg;
reg  signed [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_26_int_reg;
reg  signed [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_25_int_reg;
reg  signed [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_24_int_reg;
reg  signed [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_23_int_reg;
reg  signed [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_22_int_reg;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_21_int_reg;
reg  signed [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_20_int_reg;
reg   [36:0] ap_return_0_int_reg;
reg   [36:0] ap_return_1_int_reg;
reg   [36:0] ap_return_2_int_reg;
reg   [36:0] ap_return_3_int_reg;
reg   [36:0] ap_return_4_int_reg;
reg   [36:0] ap_return_5_int_reg;

gaussian_mul_16s_10ns_26_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_0_U12(
    .din0(mul_ln73_624_fu_166_p0),
    .din1(mul_ln73_624_fu_166_p1),
    .dout(mul_ln73_624_fu_166_p2)
);

gaussian_mul_16s_10s_26_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_0_U13(
    .din0(mul_ln73_621_fu_167_p0),
    .din1(mul_ln73_621_fu_167_p1),
    .dout(mul_ln73_621_fu_167_p2)
);

gaussian_mul_16s_9ns_25_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_0_U14(
    .din0(mul_ln73_625_fu_168_p0),
    .din1(mul_ln73_625_fu_168_p1),
    .dout(mul_ln73_625_fu_168_p2)
);

gaussian_mul_16s_7s_22_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 22 ))
mul_16s_7s_22_1_0_U15(
    .din0(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_27_int_reg),
    .din1(mul_ln73_611_fu_169_p1),
    .dout(mul_ln73_611_fu_169_p2)
);

gaussian_mul_16s_9ns_25_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_0_U16(
    .din0(mul_ln73_645_fu_170_p0),
    .din1(mul_ln73_645_fu_170_p1),
    .dout(mul_ln73_645_fu_170_p2)
);

gaussian_mul_16s_8s_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8s_24_1_0_U17(
    .din0(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_23_int_reg),
    .din1(mul_ln73_632_fu_171_p1),
    .dout(mul_ln73_632_fu_171_p2)
);

gaussian_mul_16s_8s_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8s_24_1_0_U18(
    .din0(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_25_int_reg),
    .din1(mul_ln73_620_fu_172_p1),
    .dout(mul_ln73_620_fu_172_p2)
);

gaussian_mul_16s_10ns_25_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 25 ))
mul_16s_10ns_25_1_0_U19(
    .din0(mul_ln73_604_fu_173_p0),
    .din1(mul_ln73_604_fu_173_p1),
    .dout(mul_ln73_604_fu_173_p2)
);

gaussian_mul_16s_10s_26_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_0_U20(
    .din0(mul_ln73_630_fu_174_p0),
    .din1(mul_ln73_630_fu_174_p1),
    .dout(mul_ln73_630_fu_174_p2)
);

gaussian_mul_16s_8ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8ns_24_1_0_U21(
    .din0(mul_ln73_641_fu_175_p0),
    .din1(mul_ln73_641_fu_175_p1),
    .dout(mul_ln73_641_fu_175_p2)
);

gaussian_mul_16s_8ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8ns_24_1_0_U22(
    .din0(mul_ln73_610_fu_176_p0),
    .din1(mul_ln73_610_fu_176_p1),
    .dout(mul_ln73_610_fu_176_p2)
);

gaussian_mul_16s_10s_25_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 25 ))
mul_16s_10s_25_1_0_U23(
    .din0(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_20_int_reg),
    .din1(mul_ln73_644_fu_177_p1),
    .dout(mul_ln73_644_fu_177_p2)
);

gaussian_mul_16s_8s_23_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 23 ))
mul_16s_8s_23_1_0_U24(
    .din0(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_27_int_reg),
    .din1(mul_ln73_608_fu_178_p1),
    .dout(mul_ln73_608_fu_178_p2)
);

gaussian_mul_16s_10s_26_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_0_U25(
    .din0(mul_ln73_619_fu_180_p0),
    .din1(mul_ln73_619_fu_180_p1),
    .dout(mul_ln73_619_fu_180_p2)
);

gaussian_mul_16s_10s_25_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 25 ))
mul_16s_10s_25_1_0_U26(
    .din0(mul_ln73_fu_182_p0),
    .din1(mul_ln73_fu_182_p1),
    .dout(mul_ln73_fu_182_p2)
);

gaussian_mul_16s_8ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8ns_24_1_0_U27(
    .din0(mul_ln73_609_fu_183_p0),
    .din1(mul_ln73_609_fu_183_p1),
    .dout(mul_ln73_609_fu_183_p2)
);

gaussian_mul_16s_8s_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8s_24_1_0_U28(
    .din0(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_20_int_reg),
    .din1(mul_ln73_647_fu_184_p1),
    .dout(mul_ln73_647_fu_184_p2)
);

gaussian_mul_16s_11s_27_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 27 ))
mul_16s_11s_27_1_0_U29(
    .din0(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_23_int_reg),
    .din1(mul_ln73_629_fu_185_p1),
    .dout(mul_ln73_629_fu_185_p2)
);

gaussian_mul_16s_10s_25_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 25 ))
mul_16s_10s_25_1_0_U30(
    .din0(mul_ln73_607_fu_186_p0),
    .din1(mul_ln73_607_fu_186_p1),
    .dout(mul_ln73_607_fu_186_p2)
);

gaussian_mul_16s_10s_26_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_0_U31(
    .din0(mul_ln73_612_fu_187_p0),
    .din1(mul_ln73_612_fu_187_p1),
    .dout(mul_ln73_612_fu_187_p2)
);

gaussian_mul_16s_9ns_25_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_0_U32(
    .din0(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_22_int_reg),
    .din1(mul_ln73_635_fu_188_p1),
    .dout(mul_ln73_635_fu_188_p2)
);

gaussian_mul_16s_7s_23_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 23 ))
mul_16s_7s_23_1_0_U33(
    .din0(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_24_int_reg),
    .din1(mul_ln73_627_fu_189_p1),
    .dout(mul_ln73_627_fu_189_p2)
);

gaussian_mul_16s_10s_26_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_0_U34(
    .din0(mul_ln73_636_fu_190_p0),
    .din1(mul_ln73_636_fu_190_p1),
    .dout(mul_ln73_636_fu_190_p2)
);

gaussian_mul_16s_11ns_26_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_0_U35(
    .din0(a_reg_9256),
    .din1(mul_ln73_605_fu_193_p1),
    .dout(mul_ln73_605_fu_193_p2)
);

gaussian_mul_16s_10s_25_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 25 ))
mul_16s_10s_25_1_0_U36(
    .din0(mul_ln73_606_fu_194_p0),
    .din1(mul_ln73_606_fu_194_p1),
    .dout(mul_ln73_606_fu_194_p2)
);

gaussian_mul_16s_10ns_25_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 25 ))
mul_16s_10ns_25_1_0_U37(
    .din0(a_60_reg_9292),
    .din1(mul_ln73_639_fu_195_p1),
    .dout(mul_ln73_639_fu_195_p2)
);

gaussian_mul_16s_10ns_26_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_0_U38(
    .din0(mul_ln73_637_fu_196_p0),
    .din1(mul_ln73_637_fu_196_p1),
    .dout(mul_ln73_637_fu_196_p2)
);

gaussian_mul_16s_10s_26_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_0_U39(
    .din0(mul_ln73_642_fu_197_p0),
    .din1(mul_ln73_642_fu_197_p1),
    .dout(mul_ln73_642_fu_197_p2)
);

gaussian_mul_16s_9s_25_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_1_0_U40(
    .din0(mul_ln73_617_fu_198_p0),
    .din1(mul_ln73_617_fu_198_p1),
    .dout(mul_ln73_617_fu_198_p2)
);

gaussian_mul_16s_9ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
mul_16s_9ns_24_1_0_U41(
    .din0(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_28_int_reg),
    .din1(mul_ln73_603_fu_199_p1),
    .dout(mul_ln73_603_fu_199_p2)
);

gaussian_mul_16s_9s_25_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_1_0_U42(
    .din0(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_25_int_reg),
    .din1(mul_ln73_622_fu_201_p1),
    .dout(mul_ln73_622_fu_201_p2)
);

gaussian_mul_16s_10ns_26_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_0_U43(
    .din0(mul_ln73_615_fu_202_p0),
    .din1(mul_ln73_615_fu_202_p1),
    .dout(mul_ln73_615_fu_202_p2)
);

gaussian_mul_16s_10ns_26_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_0_U44(
    .din0(mul_ln73_634_fu_203_p0),
    .din1(mul_ln73_634_fu_203_p1),
    .dout(mul_ln73_634_fu_203_p2)
);

gaussian_mul_16s_9ns_25_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_0_U45(
    .din0(mul_ln73_623_fu_204_p0),
    .din1(mul_ln73_623_fu_204_p1),
    .dout(mul_ln73_623_fu_204_p2)
);

gaussian_mul_16s_11s_27_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 27 ))
mul_16s_11s_27_1_0_U46(
    .din0(mul_ln73_646_fu_205_p0),
    .din1(mul_ln73_646_fu_205_p1),
    .dout(mul_ln73_646_fu_205_p2)
);

gaussian_mul_16s_9ns_25_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_0_U47(
    .din0(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_23_int_reg),
    .din1(mul_ln73_631_fu_206_p1),
    .dout(mul_ln73_631_fu_206_p2)
);

gaussian_mul_16s_9ns_25_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_0_U48(
    .din0(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_26_int_reg),
    .din1(mul_ln73_618_fu_207_p1),
    .dout(mul_ln73_618_fu_207_p2)
);

gaussian_mul_16s_11s_26_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_0_U49(
    .din0(mul_ln73_614_fu_209_p0),
    .din1(mul_ln73_614_fu_209_p1),
    .dout(mul_ln73_614_fu_209_p2)
);

gaussian_mul_16s_10s_26_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_0_U50(
    .din0(mul_ln73_633_fu_210_p0),
    .din1(mul_ln73_633_fu_210_p1),
    .dout(mul_ln73_633_fu_210_p2)
);

gaussian_mul_16s_9ns_24_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
mul_16s_9ns_24_1_0_U51(
    .din0(mul_ln73_640_fu_211_p0),
    .din1(mul_ln73_640_fu_211_p1),
    .dout(mul_ln73_640_fu_211_p2)
);

gaussian_mul_16s_10ns_26_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_0_U52(
    .din0(mul_ln73_613_fu_212_p0),
    .din1(mul_ln73_613_fu_212_p1),
    .dout(mul_ln73_613_fu_212_p2)
);

gaussian_mul_16s_11s_27_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 27 ))
mul_16s_11s_27_1_0_U53(
    .din0(a_60_reg_9292),
    .din1(mul_ln73_638_fu_213_p1),
    .dout(mul_ln73_638_fu_213_p2)
);

gaussian_mul_16s_10s_26_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_0_U54(
    .din0(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_20_int_reg),
    .din1(mul_ln73_648_fu_215_p1),
    .dout(mul_ln73_648_fu_215_p2)
);

gaussian_mul_16s_9s_25_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_1_0_U55(
    .din0(mul_ln73_626_fu_216_p0),
    .din1(mul_ln73_626_fu_216_p1),
    .dout(mul_ln73_626_fu_216_p2)
);

gaussian_mul_16s_11s_27_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 27 ))
mul_16s_11s_27_1_0_U56(
    .din0(mul_ln73_643_fu_217_p0),
    .din1(mul_ln73_643_fu_217_p1),
    .dout(mul_ln73_643_fu_217_p2)
);

gaussian_mul_16s_10ns_26_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_0_U57(
    .din0(mul_ln73_616_fu_218_p0),
    .din1(mul_ln73_616_fu_218_p1),
    .dout(mul_ln73_616_fu_218_p2)
);

gaussian_mul_16s_10s_26_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_0_U58(
    .din0(mul_ln73_628_fu_219_p0),
    .din1(mul_ln73_628_fu_219_p1),
    .dout(mul_ln73_628_fu_219_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        a_58_reg_9277 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_23_int_reg;
        a_59_reg_9284 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_22_int_reg;
        a_60_reg_9292 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_21_int_reg;
        a_61_reg_9298 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_20_int_reg;
        a_reg_9256 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_28_int_reg;
        add_ln58_773_reg_9308 <= add_ln58_773_fu_8620_p2;
        add_ln58_775_reg_9313 <= add_ln58_775_fu_8626_p2;
        add_ln58_776_reg_9318 <= add_ln58_776_fu_8632_p2;
        add_ln58_777_reg_9323 <= add_ln58_777_fu_8638_p2;
        add_ln58_780_reg_9328 <= add_ln58_780_fu_8644_p2;
        add_ln58_783_reg_9333 <= add_ln58_783_fu_8650_p2;
        add_ln58_785_reg_9343 <= add_ln58_785_fu_8876_p2;
        add_ln58_787_reg_9338 <= add_ln58_787_fu_8656_p2;
        add_ln58_790_reg_9348 <= add_ln58_790_fu_8911_p2;
        add_ln58_796_reg_9353 <= add_ln58_796_fu_8959_p2;
        add_ln58_799_reg_9358 <= add_ln58_799_fu_8981_p2;
        add_ln58_802_reg_9363 <= add_ln58_802_fu_8997_p2;
        add_ln58_806_reg_9368 <= add_ln58_806_fu_9003_p2;
        add_ln58_812_reg_9373 <= add_ln58_812_fu_9009_p2;
        add_ln58_816_reg_9378 <= add_ln58_816_fu_9035_p2;
        add_ln58_821_reg_9383 <= add_ln58_821_fu_9063_p2;
        mul_ln73_603_reg_2200 <= mul_ln73_603_fu_199_p2;
        mul_ln73_604_reg_7576 <= mul_ln73_604_fu_173_p2;
        mul_ln73_605_reg_7580 <= mul_ln73_605_fu_193_p2;
        mul_ln73_606_reg_2204 <= mul_ln73_606_fu_194_p2;
        mul_ln73_607_reg_2208 <= mul_ln73_607_fu_186_p2;
        mul_ln73_608_reg_2212 <= mul_ln73_608_fu_178_p2;
        mul_ln73_609_reg_2216 <= mul_ln73_609_fu_183_p2;
        mul_ln73_610_reg_2220 <= mul_ln73_610_fu_176_p2;
        mul_ln73_611_reg_2224 <= mul_ln73_611_fu_169_p2;
        mul_ln73_612_reg_2228 <= mul_ln73_612_fu_187_p2;
        mul_ln73_613_reg_2232 <= mul_ln73_613_fu_212_p2;
        mul_ln73_614_reg_7584 <= mul_ln73_614_fu_209_p2;
        mul_ln73_615_reg_7588 <= mul_ln73_615_fu_202_p2;
        mul_ln73_616_reg_7592 <= mul_ln73_616_fu_218_p2;
        mul_ln73_617_reg_8300 <= mul_ln73_617_fu_198_p2;
        mul_ln73_618_reg_7596 <= mul_ln73_618_fu_207_p2;
        mul_ln73_619_reg_7600 <= mul_ln73_619_fu_180_p2;
        mul_ln73_620_reg_7604 <= mul_ln73_620_fu_172_p2;
        mul_ln73_621_reg_7608 <= mul_ln73_621_fu_167_p2;
        mul_ln73_622_reg_7612 <= mul_ln73_622_fu_201_p2;
        mul_ln73_623_reg_7616 <= mul_ln73_623_fu_204_p2;
        mul_ln73_624_reg_7620 <= mul_ln73_624_fu_166_p2;
        mul_ln73_625_reg_7624 <= mul_ln73_625_fu_168_p2;
        mul_ln73_626_reg_8304 <= mul_ln73_626_fu_216_p2;
        mul_ln73_627_reg_7628 <= mul_ln73_627_fu_189_p2;
        mul_ln73_628_reg_7632 <= mul_ln73_628_fu_219_p2;
        mul_ln73_629_reg_7636 <= mul_ln73_629_fu_185_p2;
        mul_ln73_630_reg_8308 <= mul_ln73_630_fu_174_p2;
        mul_ln73_631_reg_7640 <= mul_ln73_631_fu_206_p2;
        mul_ln73_632_reg_7644 <= mul_ln73_632_fu_171_p2;
        mul_ln73_633_reg_8312 <= mul_ln73_633_fu_210_p2;
        mul_ln73_634_reg_7648 <= mul_ln73_634_fu_203_p2;
        mul_ln73_635_reg_7652 <= mul_ln73_635_fu_188_p2;
        mul_ln73_636_reg_7656 <= mul_ln73_636_fu_190_p2;
        mul_ln73_637_reg_7660 <= mul_ln73_637_fu_196_p2;
        mul_ln73_638_reg_8316 <= mul_ln73_638_fu_213_p2;
        mul_ln73_639_reg_8320 <= mul_ln73_639_fu_195_p2;
        mul_ln73_640_reg_7664 <= mul_ln73_640_fu_211_p2;
        mul_ln73_641_reg_7668 <= mul_ln73_641_fu_175_p2;
        mul_ln73_642_reg_7672 <= mul_ln73_642_fu_197_p2;
        mul_ln73_643_reg_8324 <= mul_ln73_643_fu_217_p2;
        mul_ln73_644_reg_7676 <= mul_ln73_644_fu_177_p2;
        mul_ln73_645_reg_8328 <= mul_ln73_645_fu_170_p2;
        mul_ln73_646_reg_8332 <= mul_ln73_646_fu_205_p2;
        mul_ln73_647_reg_7680 <= mul_ln73_647_fu_184_p2;
        mul_ln73_648_reg_7684 <= mul_ln73_648_fu_215_p2;
        mul_ln73_reg_7572 <= mul_ln73_fu_182_p2;
        sext_ln70_282_reg_9267 <= sext_ln70_282_fu_8390_p1;
        sext_ln70_290_reg_9272 <= sext_ln70_290_fu_8515_p1;
        sext_ln70_301_reg_9303 <= sext_ln70_301_fu_8580_p1;
        sext_ln73_350_reg_9261 <= sext_ln73_350_fu_8346_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= sext_ln58_261_fu_9126_p1;
        ap_return_1_int_reg <= sext_ln58_262_fu_9155_p1;
        ap_return_2_int_reg <= sext_ln58_263_fu_9175_p1;
        ap_return_3_int_reg <= sext_ln58_264_fu_9185_p1;
        ap_return_4_int_reg <= sext_ln58_265_fu_9213_p1;
        ap_return_5_int_reg <= sext_ln68_fu_9217_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_20_int_reg <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_20;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_21_int_reg <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_21;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_22_int_reg <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_22;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_23_int_reg <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_23;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_24_int_reg <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_24;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_25_int_reg <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_25;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_26_int_reg <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_26;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_27_int_reg <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_27;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_28_int_reg <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_28;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = sext_ln58_261_fu_9126_p1;
    end else begin
        ap_return_0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = sext_ln58_262_fu_9155_p1;
    end else begin
        ap_return_1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = sext_ln58_263_fu_9175_p1;
    end else begin
        ap_return_2 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = sext_ln58_264_fu_9185_p1;
    end else begin
        ap_return_3 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_4 = ap_return_4_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_4 = sext_ln58_265_fu_9213_p1;
    end else begin
        ap_return_4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_5 = ap_return_5_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_5 = sext_ln68_fu_9217_p1;
    end else begin
        ap_return_5 = 'bx;
    end
end

assign add_ln58_770_fu_8796_p2 = ($signed(mul_ln73_604_reg_7576) + $signed(25'd33185792));

assign add_ln58_771_fu_8600_p2 = ($signed(mul_ln73_606_reg_2204) + $signed(25'd33432576));

assign add_ln58_772_fu_8610_p2 = ($signed(mul_ln73_607_reg_2208) + $signed(25'd33427456));

assign add_ln58_773_fu_8620_p2 = ($signed(mul_ln73_608_reg_2212) + $signed(23'd8369152));

assign add_ln58_774_fu_8809_p2 = ($signed(sext_ln58_fu_8806_p1) + $signed(mul_ln73_reg_7572));

assign add_ln58_775_fu_8626_p2 = ($signed(sext_ln58_244_fu_8596_p1) + $signed(sext_ln73_353_fu_8382_p1));

assign add_ln58_776_fu_8632_p2 = ($signed(mul_ln73_612_reg_2228) + $signed(sext_ln58_246_fu_8606_p1));

assign add_ln58_777_fu_8638_p2 = ($signed(mul_ln73_613_reg_2232) + $signed(sext_ln58_247_fu_8616_p1));

assign add_ln58_778_fu_8828_p2 = ($signed(mul_ln73_614_reg_7584) + $signed(sext_ln58_249_fu_8819_p1));

assign add_ln58_779_fu_8838_p2 = ($signed(mul_ln73_615_reg_7588) + $signed(sext_ln58_245_fu_8802_p1));

assign add_ln58_780_fu_8644_p2 = ($signed(mul_ln73_610_reg_2220) + $signed(sext_ln73_360_fu_8496_p1));

assign add_ln58_781_fu_8847_p2 = ($signed(sext_ln58_509_fu_8844_p1) + $signed(add_ln58_779_fu_8838_p2));

assign add_ln58_782_fu_8857_p2 = (mul_ln73_605_reg_7580 + mul_ln73_616_reg_7592);

assign add_ln58_783_fu_8650_p2 = ($signed(mul_ln73_611_reg_2224) + $signed(22'd4158464));

assign add_ln58_784_fu_8866_p2 = ($signed(sext_ln58_510_fu_8863_p1) + $signed(mul_ln73_620_reg_7604));

assign add_ln58_785_fu_8876_p2 = ($signed(sext_ln58_511_fu_8872_p1) + $signed(add_ln58_782_fu_8857_p2));

assign add_ln58_786_fu_8882_p2 = ($signed(sext_ln58_248_fu_8815_p1) + $signed(sext_ln73_362_fu_8666_p1));

assign add_ln58_787_fu_8656_p2 = ($signed(sub_ln73_127_fu_8472_p2) + $signed(sext_ln73_355_fu_8424_p1));

assign add_ln58_788_fu_8891_p2 = ($signed(sext_ln58_512_fu_8888_p1) + $signed(add_ln58_786_fu_8882_p2));

assign add_ln58_789_fu_8901_p2 = (mul_ln73_619_reg_7600 + mul_ln73_624_reg_7620);

assign add_ln58_790_fu_8911_p2 = ($signed(sext_ln58_513_fu_8907_p1) + $signed(sext_ln58_252_fu_8834_p1));

assign add_ln58_791_fu_8917_p2 = ($signed(sext_ln58_251_fu_8825_p1) + $signed(mul_ln73_1205_cast_i_fu_8670_p1));

assign add_ln58_792_fu_8923_p2 = (mul_ln73_618_reg_7596 + mul_ln73_622_reg_7612);

assign add_ln58_793_fu_8933_p2 = ($signed(sext_ln58_514_fu_8929_p1) + $signed(add_ln58_791_fu_8917_p2));

assign add_ln58_794_fu_8943_p2 = ($signed(sext_ln58_253_fu_8853_p1) + $signed(sext_ln73_371_fu_8764_p1));

assign add_ln58_795_fu_8949_p2 = (mul_ln73_625_reg_7624 + mul_ln73_631_reg_7640);

assign add_ln58_796_fu_8959_p2 = ($signed(sext_ln58_515_fu_8955_p1) + $signed(add_ln58_794_fu_8943_p2));

assign add_ln58_797_fu_8965_p2 = ($signed(mul_ln73_629_reg_7636) + $signed(sext_ln58_255_fu_8897_p1));

assign add_ln58_798_fu_8971_p2 = (mul_ln73_634_reg_7648 + mul_ln73_637_reg_7660);

assign add_ln58_799_fu_8981_p2 = ($signed(sext_ln58_516_fu_8977_p1) + $signed(add_ln58_797_fu_8965_p2));

assign add_ln58_800_fu_9101_p2 = ($signed(sext_ln58_254_fu_9089_p1) + $signed(sext_ln73_363_fu_9073_p1));

assign add_ln58_801_fu_8987_p2 = (mul_ln73_640_reg_7664 + mul_ln73_632_reg_7644);

assign add_ln58_802_fu_8997_p2 = ($signed(sext_ln58_517_fu_8993_p1) + $signed(mul_ln73_635_reg_7652));

assign add_ln58_803_fu_9110_p2 = ($signed(sext_ln58_518_fu_9107_p1) + $signed(add_ln58_800_fu_9101_p2));

assign add_ln58_804_fu_9120_p2 = ($signed(sext_ln58_259_fu_9098_p1) + $signed(sext_ln73_375_fu_9081_p1));

assign add_ln58_805_fu_9130_p2 = ($signed(sext_ln58_256_fu_9092_p1) + $signed(sext_ln73_373_fu_9077_p1));

assign add_ln58_806_fu_9003_p2 = ($signed(mul_ln73_644_reg_7676) + $signed(sext_ln73_369_fu_8743_p1));

assign add_ln58_807_fu_9139_p2 = ($signed(sext_ln58_519_fu_9136_p1) + $signed(mul_ln73_630_reg_8308));

assign add_ln58_808_fu_9149_p2 = ($signed(sext_ln58_520_fu_9145_p1) + $signed(add_ln58_805_fu_9130_p2));

assign add_ln58_809_fu_9159_p2 = (mul_ln73_639_reg_8320 + mul_ln73_645_reg_8328);

assign add_ln58_810_fu_9169_p2 = ($signed(sext_ln58_521_fu_9165_p1) + $signed(sext_ln58_258_fu_9095_p1));

assign add_ln58_811_fu_9179_p2 = ($signed(sext_ln58_260_fu_9116_p1) + $signed(sext_ln73_376_fu_9085_p1));

assign add_ln58_812_fu_9009_p2 = ($signed(sext_ln58_250_fu_8822_p1) + $signed(sext_ln73_361_fu_8662_p1));

assign add_ln58_813_fu_9189_p2 = ($signed(mul_ln73_633_reg_8312) + $signed(sext_ln73_356_fu_9069_p1));

assign add_ln58_814_fu_9199_p2 = ($signed(sext_ln58_522_fu_9195_p1) + $signed(add_ln58_812_reg_9373));

assign add_ln58_815_fu_9015_p2 = (mul_ln73_641_reg_7668 + mul_ln73_647_reg_7680);

assign add_ln58_816_fu_9035_p2 = ($signed(sext_ln58_524_fu_9031_p1) + $signed(sext_ln58_523_fu_9021_p1));

assign add_ln58_817_fu_9207_p2 = ($signed(sext_ln58_525_fu_9204_p1) + $signed(add_ln58_814_fu_9199_p2));

assign add_ln58_818_fu_9041_p2 = ($signed(sext_ln58_257_fu_8939_p1) + $signed(mul_ln73_1213_cast_i_fu_8779_p1));

assign add_ln58_819_fu_9047_p2 = ($signed(mul_ln73_648_reg_7684) + $signed(sub_ln73_271_cast_fu_8707_p1));

assign add_ln58_820_fu_9053_p2 = (add_ln58_819_fu_9047_p2 + mul_ln73_642_reg_7672);

assign add_ln58_821_fu_9063_p2 = ($signed(sext_ln58_526_fu_9059_p1) + $signed(add_ln58_818_fu_9041_p2));

assign add_ln58_fu_8590_p2 = ($signed(mul_ln73_603_reg_2200) + $signed(24'd16697344));

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign mul_ln73_1205_cast_i_fu_8670_p1 = $signed(mul_ln73_628_reg_7632);

assign mul_ln73_1213_cast_i_fu_8779_p1 = $signed(mul_ln73_636_reg_7656);

assign mul_ln73_603_fu_199_p1 = 24'd184;

assign mul_ln73_604_fu_173_p0 = sext_ln73_350_reg_9261;

assign mul_ln73_604_fu_173_p1 = 25'd476;

assign mul_ln73_605_fu_193_p1 = 26'd530;

assign mul_ln73_606_fu_194_p0 = sext_ln73_350_fu_8346_p1;

assign mul_ln73_606_fu_194_p1 = 25'd33554020;

assign mul_ln73_607_fu_186_p0 = sext_ln73_350_fu_8346_p1;

assign mul_ln73_607_fu_186_p1 = 25'd33553951;

assign mul_ln73_608_fu_178_p1 = 23'd8388509;

assign mul_ln73_609_fu_183_p0 = sext_ln70_281_fu_8367_p1;

assign mul_ln73_609_fu_183_p1 = 24'd104;

assign mul_ln73_610_fu_176_p0 = sext_ln70_281_fu_8367_p1;

assign mul_ln73_610_fu_176_p1 = 24'd101;

assign mul_ln73_611_fu_169_p1 = 22'd4194250;

assign mul_ln73_612_fu_187_p0 = sext_ln70_fu_8356_p1;

assign mul_ln73_612_fu_187_p1 = 26'd67108463;

assign mul_ln73_613_fu_212_p0 = sext_ln70_fu_8356_p1;

assign mul_ln73_613_fu_212_p1 = 26'd501;

assign mul_ln73_614_fu_209_p0 = sext_ln70_283_fu_8395_p1;

assign mul_ln73_614_fu_209_p1 = 26'd67108254;

assign mul_ln73_615_fu_202_p0 = sext_ln70_283_fu_8395_p1;

assign mul_ln73_615_fu_202_p1 = 26'd279;

assign mul_ln73_616_fu_218_p0 = sext_ln70_283_fu_8395_p1;

assign mul_ln73_616_fu_218_p1 = 26'd270;

assign mul_ln73_617_fu_198_p0 = sext_ln70_282_reg_9267;

assign mul_ln73_617_fu_198_p1 = 25'd33554199;

assign mul_ln73_618_fu_207_p1 = 25'd193;

assign mul_ln73_619_fu_180_p0 = sext_ln70_287_fu_8442_p1;

assign mul_ln73_619_fu_180_p1 = 26'd67108433;

assign mul_ln73_620_fu_172_p1 = 24'd16777132;

assign mul_ln73_621_fu_167_p0 = sext_ln70_287_fu_8442_p1;

assign mul_ln73_621_fu_167_p1 = 26'd67108543;

assign mul_ln73_622_fu_201_p1 = 25'd33554226;

assign mul_ln73_623_fu_204_p0 = sext_ln70_290_fu_8515_p1;

assign mul_ln73_623_fu_204_p1 = 25'd189;

assign mul_ln73_624_fu_166_p0 = sext_ln70_289_fu_8509_p1;

assign mul_ln73_624_fu_166_p1 = 26'd465;

assign mul_ln73_625_fu_168_p0 = sext_ln70_290_fu_8515_p1;

assign mul_ln73_625_fu_168_p1 = 25'd190;

assign mul_ln73_626_fu_216_p0 = sext_ln70_290_reg_9272;

assign mul_ln73_626_fu_216_p1 = 25'd33554232;

assign mul_ln73_627_fu_189_p1 = 23'd8388564;

assign mul_ln73_628_fu_219_p0 = sext_ln70_289_fu_8509_p1;

assign mul_ln73_628_fu_219_p1 = 26'd67108442;

assign mul_ln73_629_fu_185_p1 = 27'd134217198;

assign mul_ln73_630_fu_174_p0 = sext_ln70_293_fu_8674_p1;

assign mul_ln73_630_fu_174_p1 = 26'd67108463;

assign mul_ln73_631_fu_206_p1 = 25'd236;

assign mul_ln73_632_fu_171_p1 = 24'd16777109;

assign mul_ln73_633_fu_210_p0 = sext_ln70_293_fu_8674_p1;

assign mul_ln73_633_fu_210_p1 = 26'd67108513;

assign mul_ln73_634_fu_203_p0 = sext_ln70_296_fu_8549_p1;

assign mul_ln73_634_fu_203_p1 = 26'd401;

assign mul_ln73_635_fu_188_p1 = 25'd236;

assign mul_ln73_636_fu_190_p0 = sext_ln70_296_fu_8549_p1;

assign mul_ln73_636_fu_190_p1 = 26'd67108361;

assign mul_ln73_637_fu_196_p0 = sext_ln70_299_fu_8565_p1;

assign mul_ln73_637_fu_196_p1 = 26'd303;

assign mul_ln73_638_fu_213_p1 = 27'd134217175;

assign mul_ln73_639_fu_195_p1 = 25'd276;

assign mul_ln73_640_fu_211_p0 = sext_ln70_297_fu_8559_p1;

assign mul_ln73_640_fu_211_p1 = 24'd135;

assign mul_ln73_641_fu_175_p0 = sext_ln70_297_fu_8559_p1;

assign mul_ln73_641_fu_175_p1 = 24'd106;

assign mul_ln73_642_fu_197_p0 = sext_ln70_299_fu_8565_p1;

assign mul_ln73_642_fu_197_p1 = 26'd67108590;

assign mul_ln73_643_fu_217_p0 = sext_ln70_303_fu_8791_p1;

assign mul_ln73_643_fu_217_p1 = 27'd134217116;

assign mul_ln73_644_fu_177_p1 = 25'd33554171;

assign mul_ln73_645_fu_170_p0 = sext_ln70_301_reg_9303;

assign mul_ln73_645_fu_170_p1 = 25'd154;

assign mul_ln73_646_fu_205_p0 = sext_ln70_303_fu_8791_p1;

assign mul_ln73_646_fu_205_p1 = 27'd134217101;

assign mul_ln73_647_fu_184_p1 = 24'd16777134;

assign mul_ln73_648_fu_215_p1 = 26'd67108508;

assign mul_ln73_fu_182_p0 = sext_ln73_350_reg_9261;

assign mul_ln73_fu_182_p1 = 25'd33554039;

assign sext_ln58_244_fu_8596_p1 = $signed(add_ln58_fu_8590_p2);

assign sext_ln58_245_fu_8802_p1 = $signed(add_ln58_770_fu_8796_p2);

assign sext_ln58_246_fu_8606_p1 = $signed(add_ln58_771_fu_8600_p2);

assign sext_ln58_247_fu_8616_p1 = $signed(add_ln58_772_fu_8610_p2);

assign sext_ln58_248_fu_8815_p1 = $signed(add_ln58_774_fu_8809_p2);

assign sext_ln58_249_fu_8819_p1 = $signed(add_ln58_775_reg_9313);

assign sext_ln58_250_fu_8822_p1 = $signed(add_ln58_776_reg_9318);

assign sext_ln58_251_fu_8825_p1 = $signed(add_ln58_777_reg_9323);

assign sext_ln58_252_fu_8834_p1 = $signed(add_ln58_778_fu_8828_p2);

assign sext_ln58_253_fu_8853_p1 = $signed(add_ln58_781_fu_8847_p2);

assign sext_ln58_254_fu_9089_p1 = $signed(add_ln58_785_reg_9343);

assign sext_ln58_255_fu_8897_p1 = $signed(add_ln58_788_fu_8891_p2);

assign sext_ln58_256_fu_9092_p1 = $signed(add_ln58_790_reg_9348);

assign sext_ln58_257_fu_8939_p1 = $signed(add_ln58_793_fu_8933_p2);

assign sext_ln58_258_fu_9095_p1 = $signed(add_ln58_796_reg_9353);

assign sext_ln58_259_fu_9098_p1 = $signed(add_ln58_799_reg_9358);

assign sext_ln58_260_fu_9116_p1 = $signed(add_ln58_803_fu_9110_p2);

assign sext_ln58_261_fu_9126_p1 = $signed(add_ln58_804_fu_9120_p2);

assign sext_ln58_262_fu_9155_p1 = $signed(add_ln58_808_fu_9149_p2);

assign sext_ln58_263_fu_9175_p1 = $signed(add_ln58_810_fu_9169_p2);

assign sext_ln58_264_fu_9185_p1 = $signed(add_ln58_811_fu_9179_p2);

assign sext_ln58_265_fu_9213_p1 = $signed(add_ln58_817_fu_9207_p2);

assign sext_ln58_509_fu_8844_p1 = $signed(add_ln58_780_reg_9328);

assign sext_ln58_510_fu_8863_p1 = $signed(add_ln58_783_reg_9333);

assign sext_ln58_511_fu_8872_p1 = $signed(add_ln58_784_fu_8866_p2);

assign sext_ln58_512_fu_8888_p1 = $signed(add_ln58_787_reg_9338);

assign sext_ln58_513_fu_8907_p1 = $signed(add_ln58_789_fu_8901_p2);

assign sext_ln58_514_fu_8929_p1 = $signed(add_ln58_792_fu_8923_p2);

assign sext_ln58_515_fu_8955_p1 = $signed(add_ln58_795_fu_8949_p2);

assign sext_ln58_516_fu_8977_p1 = $signed(add_ln58_798_fu_8971_p2);

assign sext_ln58_517_fu_8993_p1 = $signed(add_ln58_801_fu_8987_p2);

assign sext_ln58_518_fu_9107_p1 = $signed(add_ln58_802_reg_9363);

assign sext_ln58_519_fu_9136_p1 = $signed(add_ln58_806_reg_9368);

assign sext_ln58_520_fu_9145_p1 = $signed(add_ln58_807_fu_9139_p2);

assign sext_ln58_521_fu_9165_p1 = $signed(add_ln58_809_fu_9159_p2);

assign sext_ln58_522_fu_9195_p1 = $signed(add_ln58_813_fu_9189_p2);

assign sext_ln58_523_fu_9021_p1 = $signed(add_ln58_815_fu_9015_p2);

assign sext_ln58_524_fu_9031_p1 = $signed(sub_ln58_fu_9025_p2);

assign sext_ln58_525_fu_9204_p1 = $signed(add_ln58_816_reg_9378);

assign sext_ln58_526_fu_9059_p1 = $signed(add_ln58_820_fu_9053_p2);

assign sext_ln58_fu_8806_p1 = $signed(add_ln58_773_reg_9308);

assign sext_ln68_fu_9217_p1 = $signed(add_ln58_821_reg_9383);

assign sext_ln70_281_fu_8367_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_27_int_reg;

assign sext_ln70_281_fu_8367_p1 = sext_ln70_281_fu_8367_p0;

assign sext_ln70_282_fu_8390_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_26_int_reg;

assign sext_ln70_282_fu_8390_p1 = sext_ln70_282_fu_8390_p0;

assign sext_ln70_283_fu_8395_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_26_int_reg;

assign sext_ln70_283_fu_8395_p1 = sext_ln70_283_fu_8395_p0;

assign sext_ln70_284_fu_8402_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_26_int_reg;

assign sext_ln70_284_fu_8402_p1 = sext_ln70_284_fu_8402_p0;

assign sext_ln70_287_fu_8442_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_25_int_reg;

assign sext_ln70_287_fu_8442_p1 = sext_ln70_287_fu_8442_p0;

assign sext_ln70_289_fu_8509_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_24_int_reg;

assign sext_ln70_289_fu_8509_p1 = sext_ln70_289_fu_8509_p0;

assign sext_ln70_290_fu_8515_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_24_int_reg;

assign sext_ln70_290_fu_8515_p1 = sext_ln70_290_fu_8515_p0;

assign sext_ln70_293_fu_8674_p1 = a_58_reg_9277;

assign sext_ln70_296_fu_8549_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_22_int_reg;

assign sext_ln70_296_fu_8549_p1 = sext_ln70_296_fu_8549_p0;

assign sext_ln70_297_fu_8559_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_21_int_reg;

assign sext_ln70_297_fu_8559_p1 = sext_ln70_297_fu_8559_p0;

assign sext_ln70_299_fu_8565_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_21_int_reg;

assign sext_ln70_299_fu_8565_p1 = sext_ln70_299_fu_8565_p0;

assign sext_ln70_301_fu_8580_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_20_int_reg;

assign sext_ln70_301_fu_8580_p1 = sext_ln70_301_fu_8580_p0;

assign sext_ln70_303_fu_8791_p1 = a_61_reg_9298;

assign sext_ln70_fu_8356_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_27_int_reg;

assign sext_ln70_fu_8356_p1 = sext_ln70_fu_8356_p0;

assign sext_ln73_350_fu_8346_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_28_int_reg;

assign sext_ln73_350_fu_8346_p1 = sext_ln73_350_fu_8346_p0;

assign sext_ln73_353_fu_8382_p1 = $signed(mul_ln73_609_reg_2216);

assign sext_ln73_354_fu_8414_p1 = $signed(shl_ln_fu_8406_p3);

assign sext_ln73_355_fu_8424_p1 = $signed(sub_ln73_fu_8418_p2);

assign sext_ln73_356_fu_9069_p1 = $signed(mul_ln73_617_reg_8300);

assign sext_ln73_357_fu_8456_p1 = $signed(shl_ln73_s_fu_8448_p3);

assign sext_ln73_358_fu_8468_p1 = $signed(shl_ln73_201_fu_8460_p3);

assign sext_ln73_359_fu_8486_p1 = $signed(shl_ln73_202_fu_8478_p3);

assign sext_ln73_360_fu_8496_p1 = $signed(sub_ln73_128_fu_8490_p2);

assign sext_ln73_361_fu_8662_p1 = $signed(mul_ln73_621_reg_7608);

assign sext_ln73_362_fu_8666_p1 = $signed(mul_ln73_623_reg_7616);

assign sext_ln73_363_fu_9073_p1 = $signed(mul_ln73_626_reg_8304);

assign sext_ln73_364_fu_8686_p1 = $signed(shl_ln73_203_fu_8679_p3);

assign sext_ln73_365_fu_8697_p1 = $signed(shl_ln73_204_fu_8690_p3);

assign sext_ln73_366_fu_8718_p1 = $signed(shl_ln73_205_fu_8711_p3);

assign sext_ln73_367_fu_8729_p1 = shl_ln73_206_fu_8722_p3;

assign sext_ln73_368_fu_8733_p1 = shl_ln73_206_fu_8722_p3;

assign sext_ln73_369_fu_8743_p1 = $signed(sub_ln73_130_fu_8737_p2);

assign sext_ln73_370_fu_8754_p1 = $signed(shl_ln73_207_fu_8747_p3);

assign sext_ln73_371_fu_8764_p1 = $signed(sub_ln73_131_fu_8758_p2);

assign sext_ln73_372_fu_8775_p1 = $signed(shl_ln73_208_fu_8768_p3);

assign sext_ln73_373_fu_9077_p1 = $signed(mul_ln73_638_reg_8316);

assign sext_ln73_375_fu_9081_p1 = $signed(mul_ln73_643_reg_8324);

assign sext_ln73_376_fu_9085_p1 = $signed(mul_ln73_646_reg_8332);

assign shl_ln73_201_fu_8460_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_25_int_reg;

assign shl_ln73_201_fu_8460_p3 = {{shl_ln73_201_fu_8460_p1}, {3'd0}};

assign shl_ln73_202_fu_8478_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_25_int_reg;

assign shl_ln73_202_fu_8478_p3 = {{shl_ln73_202_fu_8478_p1}, {5'd0}};

assign shl_ln73_203_fu_8679_p3 = {{a_58_reg_9277}, {8'd0}};

assign shl_ln73_204_fu_8690_p3 = {{a_58_reg_9277}, {4'd0}};

assign shl_ln73_205_fu_8711_p3 = {{a_59_reg_9284}, {5'd0}};

assign shl_ln73_206_fu_8722_p3 = {{a_59_reg_9284}, {1'd0}};

assign shl_ln73_207_fu_8747_p3 = {{a_59_reg_9284}, {9'd0}};

assign shl_ln73_208_fu_8768_p3 = {{a_59_reg_9284}, {6'd0}};

assign shl_ln73_s_fu_8448_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_25_int_reg;

assign shl_ln73_s_fu_8448_p3 = {{shl_ln73_s_fu_8448_p1}, {6'd0}};

assign shl_ln_fu_8406_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_26_int_reg;

assign shl_ln_fu_8406_p3 = {{shl_ln_fu_8406_p1}, {5'd0}};

assign sub_ln58_fu_9025_p2 = ($signed(mul_ln73_627_reg_7628) - $signed(sext_ln73_372_fu_8775_p1));

assign sub_ln73_127_fu_8472_p2 = ($signed(sext_ln73_358_fu_8468_p1) - $signed(sext_ln73_357_fu_8456_p1));

assign sub_ln73_128_fu_8490_p2 = ($signed(22'd0) - $signed(sext_ln73_359_fu_8486_p1));

assign sub_ln73_129_fu_8701_p2 = ($signed(sext_ln73_365_fu_8697_p1) - $signed(sext_ln73_364_fu_8686_p1));

assign sub_ln73_130_fu_8737_p2 = ($signed(sext_ln73_368_fu_8733_p1) - $signed(sext_ln73_366_fu_8718_p1));

assign sub_ln73_131_fu_8758_p2 = ($signed(sext_ln73_370_fu_8754_p1) - $signed(sext_ln73_367_fu_8729_p1));

assign sub_ln73_271_cast_fu_8707_p1 = $signed(sub_ln73_129_fu_8701_p2);

assign sub_ln73_fu_8418_p2 = ($signed(sext_ln73_354_fu_8414_p1) - $signed(sext_ln70_284_fu_8402_p1));

endmodule //gaussian_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config2_mult_s
